src/framework/data/__tests__/converters.test.ts
src/framework/data/converters.ts
src/framework/data/index.ts

This just copies the converter utilities from the managed sdk into this repo. The other utils are coming.

Adopt converters from managed sdk

---

src/framework/data/__tests__/tagging.test.ts
src/framework/data/index.ts
src/framework/data/tagging.ts

Again, copied over from the managed sdk.

Adopt tagging from managed sdk

---

src/framework/data/__tests__/ip.test.ts
src/framework/data/index.ts
src/framework/data/ip.ts

I didn't see any tests for these in the managed sdk, so I added a few. There is probably a third party util out there that does a better job, but I think we can investigate that later.

Adopt ip utilities from managed sdk. Added a few tests.

---

src/framework/data/__tests__/createIntegrationRelationship.test.ts
src/framework/data/createIntegrationRelationship.ts
src/framework/data/index.ts
src/framework/jobState/FileSystemJobState/__tests__/FileSystemJobState.test.ts
src/framework/types/relationship.ts

Same thing as the `createIntegrationEntity` pr but for relationships.

Adopt create integration relationship util

---

src/__tests__/fileSystem.test.ts
src/fileSystem.ts
src/framework/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts
src/framework/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts
src/framework/storage/FileSystemGraphObjectStore/__tests__/flushDataToDisk.test.ts
src/framework/storage/FileSystemGraphObjectStore/flushDataToDisk.ts
src/framework/storage/FileSystemGraphObjectStore/indices.ts
src/framework/storage/FileSystemGraphObjectStore/path.ts

Remove input cache directory

---

.travis.yml
package.json

Add prebuild step for executing tests in ci.

Run yarn build in travis

---

CHANGELOG.md
src/framework/execution/__tests__/dependencyGraph.test.ts
src/framework/execution/dependencyGraph.ts
template/src/steps/fetchAccounts.ts

tbh I totally forgot about this and it's pretty important.

Actually log step errors

---

template/.gitignore

Just adding a few missing items.

Add .eslintcache, dist, and .j1-integration to template .gitignore

---

template/jest.config.js

Ooof. I somehow mixed up jest and webpack configs I think.

Fix jest config in template

---

docs/development.md
docs/testing.md

Born from https://github.com/JupiterOne/graph-trend-micro/pull/6#pullrequestreview-395801553. As always, a work in progress, in the end, the best approach should win, and there will need to be flexibility, but patterns are meant to capture things learned, best practices, etc., so... Would love to revisit this regularly as we implement tests across a number of integrations.

Document testing guidelines

---

CHANGELOG.md
package.json

I just created this branch to add the 0.7.0 tags.

Version 0.7.0

---

template/package.json

Template: publish dist, access public

---

src/framework/index.ts

Fixes #97 - Export all from @jupiterone/data-model

---

CHANGELOG.md
src/cli/__tests__/cli-run.test.ts
src/cli/__tests__/util/synchronization.ts
src/cli/commands/index.ts
src/cli/commands/run.ts
src/cli/index.ts
src/framework/index.ts

This also exposes some functions that we will use in our managed environment.

Add run command to cli

---

CHANGELOG.md
package.json
src/fileSystem.ts

I'll come back and write a test for this but atm trying to move quickly.

Allow storage dir to be changed via env var

---

.github/workflows/build.yml
.gitignore
CHANGELOG.md
README.md
bin/j1-integration
package.json
src/framework/api/index.ts
src/framework/execution/config.ts
testing.d.ts
testing.js
testing.ts
tsconfig.dist.json
tsconfig.json
yarn.lock

- Added `dotenv-expand` which allows `${...}` variables in `.env` file
- Changed how package is created so that it was easier to support `yarn link`
- Added support for `yarn autobuild` command

Add "yarn autobuild" command and adjust packaging to make possible

---

src/cli/__tests__/cli-run.test.ts
src/cli/commands/run.ts
src/framework/data/__tests__/createIntegrationEntity.test.ts
src/framework/data/createIntegrationEntity.ts
src/framework/execution/__tests__/executeIntegration.test.ts
src/framework/execution/executeIntegration.ts

This takes a similar approach to what the managed integration sdk did.

Allow schema validation to be disabled in managed environments

---

package.json
src/cli/__tests__/util/synchronization.ts
src/testing/recording.ts
yarn.lock

Also fixes some type errors that found when `@types/pollyjs__core` was introduced.

Move exposed @types to dependencies

---

CHANGELOG.md
src/framework/execution/__tests__/executeIntegration.test.ts
src/framework/execution/jobState.ts
src/framework/execution/types/jobState.ts
src/framework/types/entity.ts
src/testing/jobState.ts

Closes #67 I'm planning to use this in the Azure integration.

Support JobState.addEntity/Relationship, add docs

---

CHANGELOG.md

Just wanted to capture what was included while that's fresh in mind.

Update CHANGELOG.md for 1.1.1

---

CHANGELOG.md

@austinkelleher please lemme know if I've misrepresented the changes. Thanks!

Update CHANGELOG.md since 2.1.3 for 3.0.1

---

CHANGELOG.md
src/framework/execution/__tests__/dependencyGraph.test.ts
src/framework/execution/__tests__/executeIntegration.test.ts
src/framework/execution/executeIntegration.ts
src/framework/execution/validation.ts

Validate output of getStepStartStates

---

packages/integration-sdk-testing/LICENSE
packages/integration-sdk-testing/__mocks__/fs.ts
packages/integration-sdk-testing/__mocks__/graceful-fs.ts
packages/integration-sdk-testing/jest.config.js
packages/integration-sdk-testing/package.json
packages/integration-sdk-testing/src/__tests__/context.test.ts
packages/integration-sdk-testing/src/__tests__/jobState.test.ts
packages/integration-sdk-testing/src/__tests__/recording.test.ts
packages/integration-sdk-testing/src/context.ts
packages/integration-sdk-testing/src/index.ts
packages/integration-sdk-testing/src/jobState.ts
packages/integration-sdk-testing/src/logger.ts
packages/integration-sdk-testing/src/recording.ts
packages/integration-sdk-testing/tsconfig.dist.json
packages/integration-sdk-testing/tsconfig.json

Pretty self explanatory. This just adds the testing package.
Previous PR is #204, next PR is #206

Add integration-sdk-testing package

---

packages/integration-sdk/CHANGELOG.md

Forgot to do this with the last publish.

Update changelog for 2.1.0 release

---

packages/integration-sdk-testing/src/__tests__/jobState.test.ts
packages/integration-sdk-testing/src/jobState.ts

Fix jobState::getEntity by adding await in front of floating promise

---

docs/integrations/development.md
packages/integration-sdk-core/src/types/jobState.ts
packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts
packages/integration-sdk-runtime/src/execution/jobState.ts
packages/integration-sdk-testing/src/__tests__/jobState.test.ts
packages/integration-sdk-testing/src/jobState.ts
packages/integration-sdk/CHANGELOG.md

Fixes #284 - Add jobState.findEntity function

---

packages/integration-sdk-core/package.json
packages/integration-sdk/CHANGELOG.md
yarn.lock

`@jupiterone/data-model.RelationshipClass` added the class `DENIES`.

Upgrade to data-model@0.9.0

---

README.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
packages/integration-sdk/README.md
yarn.lock

Bumps @jupiterone/data-model to v0.10.0 (DomainRecord enum now allows `NS`)

Release 3.2.1

---

packages/cli/package.json
packages/cli/src/export/__tests__/bulkDownloadToJson.test.ts
packages/cli/src/export/__tests__/utils/createRelationship.ts
packages/cli/src/export/bulkDownloadToJson.ts
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Fixes https://github.com/JupiterOne/sdk/issues/248

Fixing bulkdownload payload size issue

---

packages/integration-sdk-testing/src/__tests__/jobState.test.ts
packages/integration-sdk-testing/src/jobState.ts
packages/integration-sdk/CHANGELOG.md

After this one I'm gonna create a new SDK release with some of the new features we've put in this week.

Allow setData input in createMockJobState()

---

packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts
packages/integration-sdk-runtime/src/logger/index.ts
packages/integration-sdk-testing/package.json
packages/integration-sdk/CHANGELOG.md
yarn.lock

Fixes #362 
Looks like this will need a major bump after this.

Pass `onFailure` to children of `IntegrationLogger`

---

packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
packages/integration-sdk/CHANGELOG.md
yarn.lock

Bump `@jupiterone/data-model` which introduces `RelationshipClass.APPROVED`

Upgrade @jupiterone/data-model@^0.15.0

---

packages/integration-sdk-cli/src/__tests__/cli-run-failure.test.ts
packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/fileSystem.ts
packages/integration-sdk/CHANGELOG.md

This will help show us how quickly disk usage is growing for an integration run.

Publish disk-usage on interval

---

packages/integration-sdk-runtime/src/logger/index.ts
packages/integration-sdk-runtime/src/logger/registerEventHandlers.ts
packages/integration-sdk/CHANGELOG.md

Make registerIntegrationEventEmitters call logger.onFailure

---

packages/integration-sdk-cli/src/commands/collect.ts
packages/integration-sdk-cli/src/commands/run.ts
packages/integration-sdk-cli/src/visualization/generateVisualization.ts
packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts
packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts
packages/integration-sdk-runtime/src/fileSystem.ts
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/flushDataToDisk.test.ts
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/flushDataToDisk.ts

Just more tests that didn't make it into the original continuous uploads branch yet...

Add tests for job state upload calls

---

packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/__tests__/uploadData.test.ts
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json
packages/integration-sdk/CHANGELOG.md

There is more cleanup that can be done overall to simplify this

Skip uploading when graph object array empty

---

packages/integration-sdk-core/src/types/jobState.ts
packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts
packages/integration-sdk-runtime/src/execution/jobState.ts
packages/integration-sdk-testing/src/jobState.ts
packages/integration-sdk/CHANGELOG.md

Add JobState.hasKey

---

package.json
packages/integration-sdk-private-test-utils/package.json

If packages in this project got out-of-sync, rebuilding was really confusing. Added these scripts to ease development.

Add yarn clean:build script

---

CHANGELOG.md
docs/integrations/development.md
packages/integration-sdk-core/src/types/config.ts
packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts
packages/integration-sdk-runtime/src/execution/__tests__/utils/createIntegrationConfig.ts
packages/integration-sdk-runtime/src/execution/dependencyGraph.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/execution/jobState.ts
packages/integration-sdk-runtime/src/execution/step.ts
packages/integration-sdk-runtime/src/execution/utils/getMaskedFields.ts
packages/integration-sdk-runtime/src/logger/index.ts

Fixes #470 - Introduce beforeAddEntity hook into IntegrationInvocationConfig

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Add `compare` method to `@jupiterone/integration-sdk-cli` which is used to diff data sets downloaded from JupiterOne.

release-6.4.0

---

CHANGELOG.md
packages/integration-sdk-testing/src/__tests__/jest.test.ts
packages/integration-sdk-testing/src/jest.ts

Currently using this matcher in the `graph-azure` project.

Add expect(mappedRelationships).toTargetEntities(entities) matcher

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

```
- Bump `@jupiterone/data-model` to incorporate `RelationshipClass.PUBLISHED`
```

Release 6.10.0

---

packages/integration-sdk-cli/src/visualization/__tests__/createMappedRelationshipNodesAndEdges.test.ts
packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts

Added tests per Austin's comment: https://github.com/JupiterOne/sdk/pull/515#pullrequestreview-721320817

Add test for visualize placeholder

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

```
- Added optional `mappedRelationships` to step metadata

Release 6.15.0

---

CHANGELOG.md
docs/integrations/development.md
packages/integration-sdk-cli/src/__tests__/cli.test.ts
packages/integration-sdk-cli/src/commands/collect.ts
packages/integration-sdk-cli/src/commands/diff.ts
packages/integration-sdk-cli/src/commands/document.ts
packages/integration-sdk-cli/src/commands/run.ts
packages/integration-sdk-cli/src/commands/sync.ts
packages/integration-sdk-cli/src/commands/visualize-types.ts
packages/integration-sdk-cli/src/commands/visualize.ts
packages/integration-sdk-cli/src/index.ts
packages/integration-sdk-cli/src/utils/generateVisHTML.ts
packages/integration-sdk-cli/src/visualization/__tests__/__snapshots__/generateVisHTML.test.ts.snap
packages/integration-sdk-cli/src/visualization/__tests__/generateVisHTML.test.ts
packages/integration-sdk-cli/src/visualization/__tests__/generateVisualization.test.ts
packages/integration-sdk-cli/src/visualization/generateVisualization.ts
packages/integration-sdk-cli/src/visualization/retrieveIntegrationData.ts
packages/integration-sdk-runtime/src/fileSystem.ts

Matching patterns of commander (https://github.com/tj/commander.js) descriptions etc. to bring consistency to help output.

Add --project-path, CLI improvements

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

```
- Added `toImplementSpec` jest matcher
- Added `StepSpec` and `IntegrationSpecConfig` types in order to define
integration specifications
- Changed language for relationships created that document command produces.

Release 6.19.0

---

CHANGELOG.md
docs/integrations/development.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/__tests__/cli/validate-question-file.test.ts
packages/integration-sdk-cli/src/commands/validate-question-file.ts
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

for the `--file-path` argument of `j1-integration validate-question-file`

INT-1819 - Use the default path `{CWD}/jupiterone/questions/questions.yaml`

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/__fixtures__/typeScriptIntegrationProject/src/steps/fetchUsers.ts
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
yarn.lock

- Bump `@jupiterone/data-model` to expose `RelationshipClass.HOSTS` and `RelationshipClass.LOGS`

Bump @jupiterone/data-model@0.42.0

---

packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/indices.ts

Simplify file system index iteration logic

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
yarn.lock

Bump @jupiterone/data-model to expose RelationshipClass.SENDS

Bump @jupiterone/data-model@0.43.0

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Added the `loadExecutionConfig` lifecycle method to the `InvocationConfig`
interface. `loadExecutionConfig` loads shared configuration assets, such as
shared API credentials. Example:
```ts
import { fromTemporaryCredentials } from '@aws-sdk/credential-providers';
/**
* The AWS integration uses shared `fromTemporaryCredentials` across all of
* its clients.
*/
export function loadExecutionConfig({
config: { roleArn: string, externalId: string },
}) {
return {
credentials: fromTemporaryCredentials({
params: {
RoleArn: config.roleArn,
ExternalId: config.externalId,
RoleSessionName: `juptierone-${uuid()}`,
},
}),
};
}
```

Release 8.2.0

---

packages/integration-sdk-core/src/errors.ts

Requested change by support team to help direct questions/reports to the desired channels.

Updated support contact language in error message.

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Changed logger to fully mask config field values, rather than displaying last
4 chars
- Added `.toMatchStepMetadata` jest matcher. This matcher complements the
`executeStepWithDependencies` utility. Usage:
```ts
const stepResult = await executeStepWithDependencies({
stepId: Steps.FETCH_USERS.id,
invocationConfig,
instanceConfig,
});
expect(stepResult).toMatchStepMetadata({
stepId: Steps.FETCH_USERS.id,
invocationConfig,
});
```
- Updated jest matchers in the following way:
- added optional `_type` argument to `.toMatchGraphObjectSchema` matcher
- added optional `_type` and `_class` arguments to
`.toMatchDirectRelationshipSchema` matcher
This enables developers to simply pass the `StepEntityMetadata` and
`StepRelationshipMetadata` interfaces to these matchers. Usage:
```ts …
```

Release 8.4.0

---

docs/integrations/testing.md

This PR updates `/docs/testing.md` with the new best practices for testing integration steps.

Update docs/testing.md for .toMatchStepMetadata

---

packages/integration-sdk-cli/src/neo4j/neo4jGraphStore.ts

Fixing issue causing mapped entities to have missing property data when uploaded to Neo4j.

Adding properties to mapped entities for Neo4j uploads.

---

packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- @jupiterone/cli@8.6.2
- @jupiterone/integration-sdk-benchmark@8.6.2
- @jupiterone/integration-sdk-cli@8.6.2
- @jupiterone/integration-sdk-core@8.6.2
- @jupiterone/integration-sdk-dev-tools@8.6.2
- @jupiterone/integration-sdk-private-test-utils@8.6.2
- @jupiterone/integration-sdk-runtime@8.6.2
- @jupiterone/integration-sdk-testing@8.6.2

Release v8.6.2

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 8.6.3

---

packages/integration-sdk-runtime/src/execution/uploader.test.ts
packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts
packages/integration-sdk-runtime/src/synchronization/__tests__/uploadData.test.ts
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-runtime/test/util/request.ts

INT-3119 - Pass client-generated correlation ID along with sync job uploads

---

packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts
packages/integration-sdk-runtime/src/synchronization/index.ts

Attempting to shrink rawData when we receive a 413 error that the payload size is too large.

Issue 654 - Raw data reduction

---

packages/integration-sdk-core/tsconfig.dist.json

exclude jest from dist

---

docs/integrations/development.md
packages/integration-sdk-cli/src/__tests__/cli-run.test.ts
packages/integration-sdk-cli/src/__tests__/cli-sync.test.ts
packages/integration-sdk-cli/src/__tests__/cli/validate-question-file.test.ts
packages/integration-sdk-cli/src/commands/run.ts
packages/integration-sdk-cli/src/commands/sync.ts
packages/integration-sdk-cli/src/commands/validate-question-file.ts

Add --api-base-url for sync, run, and validate-question CLI commands.

INT-3163 - Add --api-base-url for sync, run, and validate-question CLI commands

---

CHANGELOG.md
packages/integration-sdk-core/package.json
yarn.lock

Bumping `@jupiterone/data-model` to version v0.47.0.

Bumped @jupiterone/data-model version

---

packages/integration-sdk-runtime/src/synchronization/__tests__/uploadData.test.ts
packages/integration-sdk-runtime/src/synchronization/index.ts

Our max upload size of 6275072 was still giving us an error.  After discussions with Austin, we're shrinking the max size down to 1 MB.

Shrinking max upload size to 1 MB.  Updating logging.

---

CHANGELOG.md
packages/integration-sdk-core/src/errors.test.ts
packages/integration-sdk-core/src/errors.ts

This adds the new error type based on the discussions in here https://github.com/JupiterOne/sdk/issues/673

INT-3251 - Add IntegrationProviderRetriesExceededError

---

packages/integration-sdk-testing/src/__tests__/recording.test.ts
packages/integration-sdk-testing/src/recording.ts

GitHub responses base64 encode the responses after gzipping. To be able to display the full text response in human characters, we need to base64 decode prior to ungzipping.

Enhance recording.ts to support base64 encoded responses.

---

packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- @jupiterone/cli@8.13.5
- @jupiterone/integration-sdk-benchmark@8.13.5
- @jupiterone/integration-sdk-cli@8.13.5
- @jupiterone/integration-sdk-core@8.13.5
- @jupiterone/integration-sdk-dev-tools@8.13.5
- @jupiterone/integration-sdk-http-client@8.13.5
- @jupiterone/integration-sdk-private-test-utils@8.13.5
- @jupiterone/integration-sdk-runtime@8.13.5
- @jupiterone/integration-sdk-testing@8.13.5

Publish 8.13.5

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 8.13.6

---

packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- @jupiterone/cli@8.13.9
- @jupiterone/integration-sdk-benchmark@8.13.9
- @jupiterone/integration-sdk-cli@8.13.9
- @jupiterone/integration-sdk-core@8.13.9
- @jupiterone/integration-sdk-dev-tools@8.13.9
- @jupiterone/integration-sdk-http-client@8.13.9
- @jupiterone/integration-sdk-private-test-utils@8.13.9
- @jupiterone/integration-sdk-runtime@8.13.9
- @jupiterone/integration-sdk-testing@8.13.9

Publish 8.13.9

---

packages/integration-sdk-cli/src/commands/collect.ts
packages/integration-sdk-cli/src/commands/run.ts

Add --buffer-size option for collect and run commands.

Add --buffer-size option for collect and run commands.

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Added an optional `encounteredEntityKeys` property on `.toMatchStepMetadata()`
to verify that any relationship `_fromEntityKey` and `_toEntityKey` has
actually been encountered in the job state.

Release 8.16.0

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 8.17.0 bring the options to specific a separate `uploadRelationshipsBatchSize` option.
CLI flags to specify this option are `-ur` and `--upload-relationships-batch-size`.

Release 8.17.0

---

packages/integration-sdk-cli/src/log.ts
packages/integration-sdk-runtime/src/execution/__tests__/utils/processDeclaredTypesDiff.test.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/execution/index.ts
packages/integration-sdk-runtime/src/execution/utils/processDeclaredTypesDiff.ts

- Moved diffing logic to processDeclaredTypesDiff.ts
- Updated log.ts to use new method
- Added to executeIntegration.ts logging to display undeclared types.

Log when undeclared types are detected during runtime

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
yarn.lock

- Bumped `@jupiterone/data-model@v0.51.0`

Release 8.18.1

---

packages/integration-sdk-core/src/data/createIntegrationEntity.ts

This PR removes an outdated portion of the createIntegrationEntity comment.

Cleanup createIntegrationEntity

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- @jupiterone/cli@8.22.1
- @jupiterone/integration-sdk-benchmark@8.22.1
- @jupiterone/integration-sdk-cli@8.22.1
- @jupiterone/integration-sdk-core@8.22.1
- @jupiterone/integration-sdk-dev-tools@8.22.1
- @jupiterone/integration-sdk-http-client@8.22.1
- @jupiterone/integration-sdk-private-test-utils@8.22.1
- @jupiterone/integration-sdk-runtime@8.22.1
- @jupiterone/integration-sdk-testing@8.22.1

Release 8.22.1

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- @jupiterone/cli@8.22.2
- @jupiterone/integration-sdk-benchmark@8.22.2
- @jupiterone/integration-sdk-cli@8.22.2
- @jupiterone/integration-sdk-core@8.22.2
- @jupiterone/integration-sdk-dev-tools@8.22.2
- @jupiterone/integration-sdk-http-client@8.22.2
- @jupiterone/integration-sdk-private-test-utils@8.22.2
- @jupiterone/integration-sdk-runtime@8.22.2
- @jupiterone/integration-sdk-testing@8.22.2

Release 8.22.2

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 8.23.0

---

docs/integrations/development.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/commands/options.ts
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Opened https://github.com/JupiterOne/sdk/pull/793 to address the missing version in CHANGELOG. Didn't want to mess with deleting tags etc. to fix this release PR. 😬

Release 8.24.0

---

CHANGELOG.md
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/__tests__/cli-run.test.ts
packages/integration-sdk-cli/src/__tests__/cli-sync.test.ts
packages/integration-sdk-cli/src/__tests__/options.test.ts
packages/integration-sdk-cli/src/commands/collect.ts
packages/integration-sdk-cli/src/commands/options.ts
packages/integration-sdk-cli/src/commands/run.ts
packages/integration-sdk-cli/src/commands/sync.ts
packages/integration-sdk-runtime/src/api/index.ts
packages/integration-sdk-runtime/src/synchronization/index.ts
yarn.lock

Upgrade Commander and improve CLI consistency and testing

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

Adding a  log to capture the completion of uploads.

add log to upload data

---

packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts
packages/integration-sdk-runtime/src/execution/dependencyGraph.ts
packages/integration-sdk-runtime/src/execution/jobState.ts

This PR enables the step summary output to be more queryable by various log searching tools.

enhance sdk step output

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release v8.30.0 updating step summary formatting

Release 8.30.0

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Update `assignTags()` to add keys with `value: ''` to entity `.tags` property

CHANGELOG for 8.30.4

---

package.json
packages/cli/src/__tests__/cli-export.test.ts
packages/cli/src/__tests__/cli-import.test.ts
packages/cli/src/export/__tests__/bulkDownloadToJson.test.ts
packages/cli/src/export/__tests__/exportAssetsToJson.test.ts
packages/integration-sdk-cli/src/__tests__/cli-run-failure.test.ts
packages/integration-sdk-cli/src/visualization/__tests__/generateVisualization.test.ts
packages/integration-sdk-cli/src/visualization/__tests__/retrieveIntegrationData.test.ts
packages/integration-sdk-runtime/src/api/__tests__/index.test.ts
yarn.lock

I've seen the warning one to many times to ignore it!

update mocked to use jest-mock

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
yarn.lock

Updating the `@jupiterone/data-model` version.

update data model version

---

CHANGELOG.md
packages/integration-sdk-runtime/src/storage/memory.test.ts
packages/integration-sdk-runtime/src/storage/memory.ts

Add collectEntities and collectRelationships to InMemoryGraphObjectStore

add: collectEntites and collectRelationships

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release #852

---

CHANGELOG.md
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Reverts the previous publish command so that we can attempt to republish
- Revert "Merge pull request #857 from JupiterOne/INT-7594-uuid-version"
- Revert "Publish"

revert to before major version

---

lerna.json
package.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json
yarn.lock

This reverts commit e3d175728de87a9e1aa0e00c9ed2e27c6a1ffc83, reversing
changes made to 8827312264d62721523f04c31246ba45cd521c37.

Revert "Merge pull request #861 from JupiterOne/release-9.0.0"

---

CHANGELOG.md
lerna.json
package.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 8.33.0

---

.prettierignore
CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Added support for `json` environment variables. Example:
`.env` file:
```
// .env
SEVERITIES=["HIGH", "CRITICAL"]
```
Code:
```ts
import { Client } from './client';
import { createVulnEntity } from './converter';
type IntegrationConfig = { apiKey: string; severities: string[] };
const invocationConfig: IntegrationInvocationConfig = {
instanceConfigFields: [
{
apiKey: { type: 'string', mask: true },
severities: { type: 'json' },
},
],
integrationSteps: [
{
id: 'fetch-vulnerabilities',
name: 'Fetch Vulnerabilities',
entities: [{ resourceName: 'Vuln', _type: 'vuln', _class: 'Finding' }],
relationships: [],
executionHandler: ({ instance }) => {
const { apiKey, severities } = instance.config;
const client = new Client({ apiKey });
await iterateVulnerabilitiesForSeverity(
{ severities }, …
```

Release 8.34.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

PR with all the logic and changes https://github.com/JupiterOne/sdk/pull/865

Release 8.35.0

---

lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

v9.0.0-beta.1

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.test.ts
packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

PR already approved to `main` here https://github.com/JupiterOne/sdk/pull/886

Release 8.38.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

See: https://github.com/JupiterOne/sdk/pull/879
Cherry-picked the following commits from `v8` branch:
- https://github.com/JupiterOne/sdk/commit/265d6141e42c4a604cbb28b3b3558dab0594c57e
- https://github.com/JupiterOne/sdk/commit/dcb79fda6bc97287356c6c107fd539e12b790dd8

Release SDK v9

---

CHANGELOG.md
packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts
packages/integration-sdk-runtime/src/execution/__tests__/utils/getIngestionSourceStepStartStates.test.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/execution/utils/getIngestionSourceStepStartStates.ts

Depends on https://github.com/JupiterOne/sdk/pull/894 to be released first

INT-7563: modify stepStartStates based on disabledSources

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release9.3.0

---

packages/integration-sdk-core/src/types/step.ts
packages/integration-sdk-runtime/src/execution/__tests__/utils/getIngestionSourceStepStartStates.test.ts
packages/integration-sdk-runtime/src/execution/utils/getIngestionSourceStepStartStates.ts
packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts
packages/integration-sdk-runtime/src/logger/index.ts

Add new DisabledStepReason for IngestionSource feature
Update existing DisabledStepReason.CONFIG message

Add user config disabled reason

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

We have seen some increased error rates in AWS integration due to sync initialization. Logging to get more information.

Log sync initialize/finalize errors

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

Run prettier for the changes in 9.6.1

Int 8625 log initialize finalize sync errors

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 9.11.0

---

.prettierrc
CHANGELOG.md
package.json
packages/cli/src/export/groupJsonAssetsByType.ts
packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts
packages/integration-sdk-core/src/types/config.ts
packages/integration-sdk-core/src/types/context.ts
packages/integration-sdk-dev-tools/config/prettier.js
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts
packages/integration-sdk-runtime/src/execution/__tests__/utils/createIntegrationConfig.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/execution/jobState.ts
packages/integration-sdk-runtime/src/execution/utils/getMaskedFields.ts
packages/integration-sdk-runtime/src/logger/index.ts
packages/integration-sdk-testing/src/config.ts
yarn.lock

- First commit includes the raw package upgrade
- Second commit runs the prettier format on the whole project

Upgrade prettier to v3

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/api/index.ts
packages/integration-sdk-testing/package.json
yarn.lock

- fix: allow Lambda class to be pased to Alpha
- update CHANGELOG

Allow Lambda to be Passed to Alpha

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 10.3.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Revert change in 10.1.0 due to system health issues

Release 10.4.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/README.md
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/generator/template/.github/workflows/build.yml.hbs
packages/integration-sdk-cli/src/generator/template/.github/workflows/codeql-analysis.yml.hbs
packages/integration-sdk-cli/src/generator/template/.github/workflows/integration-deployment.yml.hbs
packages/integration-sdk-cli/src/generator/template/.github/workflows/peril.yml.hbs
packages/integration-sdk-cli/src/generator/template/.github/workflows/questions.yml.hbs
packages/integration-sdk-cli/src/generator/template/package.json.hbs
packages/integration-sdk-cli/src/generator/template/src/config.ts.hbs
packages/integration-sdk-cli/src/generator/template/src/steps/constants.ts.hbs
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Fix github flow
- Improve types
- Update dependencies
- Update README

Improve integration generator

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release v11.0.3

---

CHANGELOG.md
packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts
packages/integration-sdk-cli/src/commands/generate-integration-graph-schema.ts
packages/integration-sdk-cli/src/config.ts

Allows loading modules by their name rather than absolute path.

Add Module Support in CLI

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 11.1.0

---

packages/integration-sdk-runtime/src/execution/dependencyGraph.ts
packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts
packages/integration-sdk-runtime/src/logger/index.ts

- [INT-9711] Add duration field to log, and change start/stop messages to debug
- Update test
[INT-9711]: https://jupiterone.atlassian.net/browse/INT-9711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[INT-9771] Change extraneous log statements to debug and add duration to summary

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 11.3.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 11.3.1

---

packages/integration-sdk-cli/src/visualization/generateVisualization.ts

Add region and _key to visualize

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

release 11.4.0

---

packages/integration-sdk-runtime/src/execution/executeIntegration.ts

The overall feature is better explained here: https://github.com/JupiterOne/callisto/pull/418
The change done here allows a function to be called to do something with the results of an integration job.
That's needed for this feature so that the managed runtime can use that callback function to store the job's output in S3 (https://github.com/JupiterOne/jupiter-managed-integration/pull/353).
---
Jira Ticket: [INT-9047 Make Summary.json available (to TAM or users)
](https://jupiterone.atlassian.net/browse/INT-9047)

INT-9047 Make Summary.json available (to TAM or users)

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

I did the last release incorrectly. Hopefully attempt 2 works.

Release v11.5.1

---

CHANGELOG.md
README.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Release 11.5.2

---

packages/integration-sdk-core/src/types/config.ts
packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts
packages/integration-sdk-runtime/src/execution/duplicateKeyTracker.ts
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-runtime/src/execution/utils/bigMap.ts

Add ability to return encountered keys in job output

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

The reason behind bumping the minor, is due to data-model changes.
https://github.com/JupiterOne/data-model/compare/v0.54.0...v0.55.0

Release 12.3.0

---

packages/integration-sdk-cli/package.json
packages/integration-sdk-runtime/src/execution/dependencyGraph.ts
yarn.lock

Fixes a statement that is never reached. Bumps `json-diff` dependency to fix a transitive dependency resulting in a bad bundle.

fix unneeded statement, bump json-diff dep

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Release `@jupiterone/integration-sdk-entity-validator` first version

Release v12.5.0

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Releasing `OnDiskDuplicateKeyTracker` alpha version

Alpha release v12.7.0-alpha.0

---

CHANGELOG.md
packages/integration-sdk-core/package.json
packages/integration-sdk-core/src/data/createIntegrationEntity.ts
packages/integration-sdk-core/tsconfig.json
yarn.lock

`validateEntityWithSchema` will be removed from `data-model`

[APP-15141] - Replace validateEntityWithSchema

---

CHANGELOG.md
packages/integration-sdk-entity-validator/src/j1Formats.ts

Add asn format for validation in IpRange schema

Add asn format

---

CHANGELOG.md
lerna.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/execution/executeIntegration.ts
packages/integration-sdk-testing/package.json

Adding an env variable to disable the collection of metrics. It seems that these may be causing some memory leak issues.

No Collection Metrics

---

CHANGELOG.md
packages/integration-sdk-core/package.json
packages/integration-sdk-core/src/data/__tests__/createIntegrationHelpers.test.ts
packages/integration-sdk-core/src/data/createIntegrationHelpers.ts

Thanks to @hesto2 and @ryan-willis for the collab 🤙

APP-15223 - Fix typing for createIntegrationHelpers

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

- Stop flushing after a step completes.
- General flushing optimizations.
- Mark as partials all types releated to failed uploads.

Release 13.0.0 🚀 

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Will release this change: https://github.com/JupiterOne/sdk/pull/1106

Release 13.3.0

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-core/src/types/jobState.ts
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts
packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/indices.ts
packages/integration-sdk-runtime/src/storage/memory.ts
packages/integration-sdk-testing/package.json

Add concurrency parameter to the iterateEntities and iterateRelationship methods.

add-concurrency-to-iterate

---

lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

To rule out a mutation to the entity, add logging prior to upload.

Add logging for aws_s3_bucket entities prior to upload

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-core/src/types/logger.ts
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts
packages/integration-sdk-runtime/src/synchronization/index.ts
packages/integration-sdk-testing/package.json

to finalizeSynchronization and abortSynchronization methods. Added tests. Added steps_finished Event Name

INT-11895: Add Retry logic

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-http-client/package.json
packages/integration-sdk-http-client/src/client.ts
packages/integration-sdk-http-client/src/types.ts
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

Added argent option to the http client in order to be able to customize that in the integrations itself

Release 13.7.2

---

packages/integration-sdk-runtime/src/execution/executeIntegration.ts

Remove comments to validate problem with ISO

No ticket remove comments

---

CHANGELOG.md
lerna.json
package-lock.json
packages/cli/package.json
packages/integration-sdk-benchmark/package.json
packages/integration-sdk-cli/package.json
packages/integration-sdk-cli/src/__tests__/cli.test.ts
packages/integration-sdk-core/package.json
packages/integration-sdk-dev-tools/package.json
packages/integration-sdk-entities/package.json
packages/integration-sdk-entity-validator/package.json
packages/integration-sdk-entity-validator/src/j1Formats.ts
packages/integration-sdk-http-client/package.json
packages/integration-sdk-private-test-utils/package.json
packages/integration-sdk-runtime/package.json
packages/integration-sdk-testing/package.json

When running validation, user should see something to this effect but the validation will not fail.

Release 16.0.0

---

packages/integration-sdk-core/src/errors.ts
packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts

to only include the support email.

Updated the unexpected error message 
