JupiterOne/sdk

__mocks__/fs.ts, package.json, src/__tests__/cacheDirectory.test.ts, src/cacheDirectory.ts, yarn.lock
This adds a `cacheDirectory` utility that will be shared by both the `jobState` and CLI. The goal of this util is to provide an interface for writing data relative to some specified directory (the cache directory). The two functions implemented are for writing data and will be used by the `jobState` as data is flushed. Additional functions to help with iterating through files will come as the `iterateEntities` and `iterateRelationship` functions are implemented.
Normally I would use library like `fs-extra` to assist with writing files (does `mkdir -p` for you) but now that node's built-in `fs` lib has much better promise support and a recursive option with `mkdir`, I decided `fs-extra` added little value. 
An additional benefit of sticking with regular `fs` is that we can use tools like …
=> Implement cache directory utilities needed for jobState

src/__tests__/cacheDirectory.test.ts, src/cacheDirectory.ts, src/framework/jobState/FileSystemJobState/FileSystemJobState.ts, src/framework/jobState/FileSystemJobState/__tests__/FileSystemJobState.test.ts, src/framework/jobState/FileSystemJobState/flushDataToDisk.ts, src/framework/jobState/FileSystemJobState/indices.ts, src/framework/jobState/FileSystemJobState/path.ts
This PR implements the `iterateEntities` and `iterateRelationships` functions. I added a function for recursively walking a directory to read files and used that for implementing iterate functions. It's a bit overkill right now, but was quick to implement and will be needed when we start working on the synchronization command anyway.
=> Implement jobstate iterate functions

package.json, src/framework/execution/__tests__/executeIntegration.test.ts, src/framework/execution/__tests__/logger.test.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/logger.ts, src/framework/execution/types/context.ts, src/framework/execution/types/index.ts, src/framework/execution/types/logger.ts, testSetup.ts, yarn.lock
This PR mostly adopts the integration logger implementation that already existed in the managed integration sdk. 
I changed a few small things. For example, the creating a logger no longer requires an `INTEGRATION_NAME` environment variable to be supplied. I think we can fetch that from the integration definition during managed runs and provide a default value during local runs.
Note: this doesn't include any special handling of `logger.auth` or `logger.error` messages.
=> Add basic integration logger

src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/dependencyGraph.ts, src/framework/execution/types/context.ts, src/framework/execution/types/step.ts
Small change. I realized that I forgot to have `IntegrationStepExecutionContext` extend the `IntegrationExecutionContext`. This change will make it so that typescript devs don't go crazy over not having access to the `logger` on the context when it really is there.
=> Make IntegrationStepExecutionContext extend IntegrationExecutionContext

package.json, tsconfig.dist.json
Building now actually references the tsconfig.dist.json file.
The dist directory now follows the same structure as src.
=> Improve prepublish transpilation

package.json, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/__tests__/logger.test.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/index.ts, src/framework/execution/logger.ts, yarn.lock
Some small tweaks to the integration logger to allow for pretty logging when running the integration locally. I tried mucking around a little to see if the formatter script that ships with bunyan could be used (normally done by piping output into `yarn bunyan` or `npx bunyan`), but tbh that ended up feeling pretty hacky.  
Here's what output would look like with the cli that's coming:
=> Add option for pretty logging for later use with local collection

__mocks__/fs.ts, package.json, src/framework/data/__tests__/createIntegrationEntity.test.ts, src/framework/data/createIntegrationEntity.ts, src/framework/data/index.ts, src/framework/data/validation.ts, src/framework/jobState/FileSystemJobState/__tests__/FileSystemJobState.test.ts, src/framework/types/entity.ts, src/framework/types/index.ts, yarn.lock
This copies over the `createIntegrationEntity` utilities and tweaks some of the types a bit to allow the  `Entity` type defined in this repo to play nicely.
=> Adopt create integration entity util

package.json, src/cli/__mocks__/log.ts, src/cli/__tests__/__fixtures__/typeScriptProject/src/getStepStartStates.ts, src/cli/__tests__/__fixtures__/typeScriptProject/src/instanceConfigFields.json, src/cli/__tests__/__fixtures__/typeScriptProject/src/steps/fetchAccounts.ts, src/cli/__tests__/__fixtures__/typeScriptProject/src/steps/fetchUsers.ts, src/cli/__tests__/__fixtures__/typeScriptProject/src/validateInvocation.ts, src/cli/__tests__/config.test.ts, src/cli/config.ts, src/cli/log.ts, yarn.lock
This PR adds loading in an integration's invocation config based on an project structure convention.
Expected structure relative to where the cli is run.
```
src/instanceConfigFields.json
src/validateInvocation.ts
src/getStepStartStates.ts
src/steps/*
```
ATM this works for both typescript and javascript projects, but I only wrote tests for typescript projects now since that's our target audience this week. I'll add tests to ensure plain js projects work down the road (would be quick).
Let me know if you want changes to where files should live.
=> Add project convention file loading for later use with cli

template/.prettierrc, template/CHANGELOG.md, template/prettier.config.js
Switch prettier config to .prettierrc to match other config files (small bonus change while I'm in this dir)
I think we should (going forward) keep a changelog for integrations. It will help consumers of our integrations understand the changes being made to their graph.
=> Add CHANGELOG.md to template to encourage documenting changes

template/src/validateInvocation.ts
Got some feedback from @ndowmon that this should be async to help represent that a promise can be returned.
=> Make validateInvocation function in template async

package.json, src/framework/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts
We have these rules off in our [internal eslint config](https://bitbucket.org/lifeomic/typescript-tools/src/27c6707b50776a6d361cc9d41c1e6fd1a35e5831/config/eslint-base.json#lines-16).
The tests that have the `expect.assertions(0)` do not have assertions because they are typescript "fit" tests.
=> Suppress eslint warnings

template/.github/workflows/build.yml
Github only looks at the `.github/workflows` dir from the root for determining if there's an action to perform, so keeping this in the template is safe.
=> Add build workflow for template projects

.eslintignore, CHANGELOG.md, docs/development.md, docs/testing.md, src/testing/__tests__/context.test.ts, src/testing/context.ts, src/testing/index.ts, src/testing/logger.ts, testing.d.ts, testing.js, tsconfig.dist.json, tsconfig.json
This PR exposes a method of exposing testing utilities from `@jupiterone/integration-sdk/testing`. The first utility exposed is a `createMockExecutionContext` function to help construct a context object for unit testing the `validateInvocation` and `getStartStepStates` functions.
Exposing testing utils from the `@jupiterone/integration-sdk/testing` helps avoid stuffing in non-essential components of integration execution in the core runtime and keeps the main interface lean.
=> Create context test util

CHANGELOG.md, package.json
Tiny change to make it clear what versions of node we expect consumers to use this with. It's explicit about `10.x` and `12.x` because that's what we run tests against.
=> Specify node engines in package.json

CHANGELOG.md, docs/testing.md, src/testing/__tests__/context.test.ts, src/testing/__tests__/jobState.test.ts, src/testing/context.ts, src/testing/jobState.ts
I'm hoping that this function + the easier access to collected data from the `jobState` + Polly.js should make testing steps easy.
=> Add createMockStepExecutionContext function to testing lib

CHANGELOG.md, docs/testing.md, src/__tests__/loadProjectStructure.ts, src/framework/config.ts, src/testing/__tests__/context.test.ts, src/testing/context.ts
This should help out with setting up test scenarios when developing locally without having devs need to manually set environment variables or use `dotenv`.
I removed some logging from the individual `load*` functions exposed by `src/framework/config.ts` because I didn't want those messages to add to test output. IMO those messages are not super useful anyway. If we find it's worth bringing back those messages, I say we do it with more useful messaging (ex. "x file was detected, loading") and in a separate PR.
=> Use .env to load instance config when using mock context

CHANGELOG.md, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/dependencyGraph.ts, src/framework/execution/types/step.ts
This fixes an issue with steps being prematurely kicked off before previous steps have fully completed their work.
=> Fix issue dependency graph execution not waiting until dependencies have completed

CHANGELOG.md, docs/testing.md, src/testing/__tests__/recording.test.ts, src/testing/recording.ts
Some of my integration tests include `404` responses from `user` endpoints, and users are instead recorded with abridged data (name, email, userId).
I would like to pass all of the `PollyOptions` through `setupRecording` so that developers can use options like `recordFailedRequests: true` while creating integrations.
=> add polly config optios to setupRecording

CHANGELOG.md, src/__tests__/__fixtures__/instanceWithDependentSteps/.gitignore, src/framework/execution/__tests__/executeIntegration.test.ts, src/framework/execution/executeIntegration.ts
As described in the [partial datasets](https://github.com/JupiterOne/integration-sdk/blob/master/docs/development.md#letting-the-synchronizer-know-about-partial-datasets) section of the sdk docs, the metadata from the summary will be used when finalizing the synchronization job. Having the summary on disk is helpful when performing the `sync` command (which I may soon be doing a lot of).
=> Write summary.json

package.json, src/framework/data/__tests__/createIntegrationEntity.test.ts, yarn.lock
Looks since the last installed version, the data model added the `id` to the whitelisted source properties so I had to update a test.
=> Update data model to the latest version

CHANGELOG.md, src/testing/__tests__/recording.test.ts, src/testing/recording.ts
The root of the issue is that a post body sent that is gunzipped won't get persisted correctly to the `.har` files because of this:
https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/persister/src/har/request.js#L42
The value of the `request.body` can't be changed post flight, because the object it inherits from is frozen once the request finishes so that the request can be uniquely identified.  Therefore I added in a function to change the value preflight...
https://github.com/Netflix/pollyjs/blob/master/packages/%40pollyjs/core/src/-private/http-base.js#L103
Example usage of this:
```
mutateRequest: (request) => {
const contentEncoding = request.getHeader('content-encoding');
if (contentEncoding === 'gzip') {
const unzippedBody = zlib.unzipSync(request.body); …
```
=> NO-TICKET - add mutateRequest function to change the request object preflight.

src/framework/data/__tests__/createIntegrationEntity.test.ts, src/framework/data/createIntegrationEntity.ts
@aiwilliams and I noticed that when properties that line up with https://github.com/JupiterOne/data-model/tree/master/src/schemas are null they cause an exception to be thrown when calling createIntegrationEntity. This fix removes those properties from the whitelist of properties to be validated against the schema, but still allows those properties to be written to the entity created.
=> Allowing source objects to have null/undefined properties

package.json, template/.eslintrc, template/package.json, yarn.lock
I upgraded my setup to actually work with `eslint` correctly and started to feel the pain others have. Turns out I got the eslint prettier plugin and config mixed up. The config disables eslint styling rules and the plugin turns them on. I don't think we use any eslint configs that make styling choices, but it's probably better to ensure that all of them are off and do not conflict with prettier just to be safe.
Reference: https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules
Shoutout to @ndowmon for figuring out that removing the plugin got rid of formatting rules.
=> Fix issue with prettier disable not working correctly

CHANGELOG.md, src/framework/execution/__tests__/executeIntegration.test.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/index.ts, src/framework/index.ts
Provides ability to execute an instance without local, generated input. This does not address some other necessary changes, such as `loadConfig("node_module/@jupiterone/graph-trend-micro/dist")`, or `syncronize(...)` and `finalize(...)` with different J1 API clients.
=> Allow external instance execution

package.json
I already updated the `CHANGELOG.md` for `v0.16.0` (which I shouldn't have done) so I don't need to update it again.
This was the `CHANGELOG.md` entry:
```
- Added support for `yarn autobuild` command to make it easier to build and link
`@lifeomic/integration-sdk` into other projects.
- Add `dotenv-expand` which allows expansion of `${...}` variables in `.env`
file.
- Add **Integration SDK Development** section to `README.md`
```
=> 0.16.0 release

CHANGELOG.md, src/framework/execution/error.ts
This will be used by the managed integration environment to complain when it cannot load a config.
=> Add IntegrationConfigLoadError type

.huskyrc.js, CHANGELOG.md, template/.huskyrc, template/package.json
The `yarn build` used to run the tests in `prebuild`, but that was lost with `autobuild` changes in last release.
=> Fix template, replace test run in pre-push

src/cli/__tests__/cli.test.ts, src/framework/__tests__/config.test.ts
Started seeing some warnings about require.cache access while doing other so decided to address this rnrq. I originally added the `require.cache` clearing and `jest.resetModules` because I wanted to be cautious in tests when performing fixture loading, but this isn't really an issue.
=> Remove usage of jest.resetModules and require.cache access

CHANGELOG.md, src/cli/__tests__/util/synchronization.ts, src/cli/commands/run.ts, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/__tests__/logger.test.ts, src/framework/execution/dependencyGraph.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/logger.ts, src/framework/execution/types/logger.ts, src/framework/synchronization/index.ts, src/testing/__tests__/context.test.ts, src/testing/logger.ts
As per, what we have in the [development document](https://github.com/JupiterOne/integration-sdk/blob/master/docs/development.md#logger) around logging, this felt like a good time to experiment with instrumenting the logger with new functions that perform both event publishing and traditional logging.
=> Add step event publishing functions to logger

CHANGELOG.md, src/__tests__/__fixtures__/validationFailure/src/steps/fetchUsers.ts, src/__tests__/__fixtures__/validationFailure/src/validateInvocation.ts, src/cli/__tests__/cli-run-failure.test.ts, src/cli/__tests__/cli-run.test.ts, src/cli/__tests__/util/synchronization.ts, src/cli/commands/run.ts, src/framework/execution/logger.ts, src/framework/execution/types/logger.ts, src/framework/synchronization/__tests__/index.test.ts, src/framework/synchronization/index.ts, src/testing/__tests__/context.test.ts, src/testing/logger.ts
I setup the logger to track previously logged errors so that we can avoid duplicate logging at the final `catch`. Mutating the error as it bubbled up felt a little dirty, so I set up tracking via a `Set`. I don't feel too strongly about any approach though.
=> Abort synchronization job on failure

CHANGELOG.md, src/__tests__/__fixtures__/indexFileEntrypoint/src/index.ts, src/__tests__/__fixtures__/indexFileEntrypointFailure/src/index.ts, src/framework/__tests__/config.test.ts, src/framework/config.ts, template/src/index.ts, template/src/instanceConfigFields.json, template/src/instanceConfigFields.ts
Addresses #124. I'm only deprecating the convention style loading for now and not removing things entirely so that others that are actively working on integrations can still pick up some changes (data model upgrades or small additions) without breaking their integration.
I want to add better validation and potentially introduce some type-gen or other tool to help keep static types and runtime validation code in sync. That may become a larger change and what's here is enough to allow us to start making deploys easier with the managed runtime. When we do the 1.0.0 release, we'll drop the convention loading entirely.
=> Support loading invocation config from src/index

CHANGELOG.md, src/__tests__/generateSynchronizationJob.ts, src/cli/__tests__/cli-run-failure.test.ts, src/cli/__tests__/util/synchronization.ts, src/cli/commands/run.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/logger.ts, src/framework/execution/types/logger.ts, src/framework/synchronization/__tests__/index.test.ts, src/framework/synchronization/index.ts, src/framework/synchronization/types.ts, src/testing/__tests__/context.test.ts, src/testing/logger.ts
This adds logging to end of the synchronization finalize and data collection functions so that the runtime doesn't need to add the information itself.
Tweaks `logger.registerSynchronizationJobContext` to return a child logger
with added information from the synchronizationJob.
Tweaks `initiateSynchronization` to perform the `logger.registerSynchronizationJobContext`
instead of just creating a child logger.
=> Add additional data from synchronization jobs to logs

CHANGELOG.md, src/errors.ts, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/config.ts, src/framework/execution/error.ts
Advances #156. I think we can start with these, but we'll also need something like @charlieduong94 mentioned, `logger.authError`, both for the integration-sdk to use when that type of error is thrown from a step, as well as by the step itself when it doesn't want to terminate, only report that and move on to some other work.
=> Add some types of execution errors

CHANGELOG.md, src/framework/execution/dependencyGraph.ts, src/framework/execution/jobState.ts, src/framework/execution/types/jobState.ts, src/testing/__tests__/jobState.test.ts, src/testing/jobState.ts
Advances #131.
I wonder if `JobState` is the right place to put something like this, because it seems that object is focused on interfacing with the `GraphObjectStore`. An alternative would be to have this kind of thing on the `IntegrationStepExecutionContext` itself.
I'd like to have this in the Azure integration to store the singleton `Account` entity in the first step that other steps depend on to build relationships to the account. Compare to using `iterateEntities` to find the single object.
Please provide any feedback you have on how this might be improved/better satisfy #131.
=> Add JobState.set/getData

CHANGELOG.md, package.json, src/__tests__/__fixtures__/typeScriptIntegrationProject/src/steps/fetchAccounts.ts, src/__tests__/__fixtures__/typeScriptIntegrationProject/src/steps/fetchUsers.ts, src/errors.ts, src/framework/config.ts, src/framework/data/createIntegrationEntity.ts, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/config.ts, src/framework/execution/dependencyGraph.ts, src/framework/execution/instance.ts, src/framework/execution/logger.ts, src/framework/execution/step.ts, src/framework/execution/types/config.ts, src/framework/execution/types/context.ts, src/framework/execution/types/instance.ts, src/framework/execution/types/step.ts, src/framework/execution/types/validation.ts, src/framework/types/entity.ts, src/testing/context.ts, src/testing/recording.ts, template/src/index.ts, template/src/steps/fetchAccounts.ts, template/src/types.ts, template/src/validateInvocation.ts
Closes #70. I'm using this in the Azure integration, using `yarn link` (and `autobuild` @philidem !). It's great.
=> Make IntegrationInstance.config a generic type

CHANGELOG.md, src/framework/execution/error.ts
`code`, `fatal`, `message` are provided by the error constructors and should not be provided at all by code throwing these types.
=> Fix API error constructor options

docs/development.md, package.json, src/__tests__/log.test.ts, src/cli/__tests__/cli-run.test.ts, src/cli/__tests__/cli.test.ts, src/cli/commands/collect.ts, src/framework/config.ts, src/framework/execution/__tests__/dependencyGraph.test.ts, src/framework/execution/__tests__/executeIntegration.test.ts, src/framework/execution/__tests__/logger.test.ts, src/framework/execution/__tests__/validation.test.ts, src/framework/execution/dependencyGraph.ts, src/framework/execution/error.ts, src/framework/execution/executeIntegration.ts, src/framework/execution/index.ts, src/framework/execution/jobState.ts, src/framework/execution/logger.ts, src/framework/execution/step.ts, src/framework/execution/types/config.ts, src/framework/execution/types/context.ts, src/framework/execution/types/logger.ts, src/framework/execution/types/step.ts, src/framework/execution/types/validation.ts, src/framework/execution/validation.ts, src/framework/index.ts, src/framework/synchronization/index.ts, src/log.ts, src/testing/index.ts
A user may want to execute some steps but not tie the execution to a specific integration instance, but rather just follow the same patterns as the managed integrations.
=> Initial changes to decompose integration execution functionality

CHANGELOG.md, tsconfig.dist.json
I'm running into this stack trace:
```
Configuration loaded! Running integration...
TypeError: Cannot read property 'disabled' of undefined
at /Users/aiwilliams/Workspaces/jupiterone-io/graph-azure/node_modules/@jupiterone/integration-sdk/src/framework/execution/dependencyGraph.js:247:46
at Array.map (<anonymous>)
at buildStepResultsMap (/Users/aiwilliams/Workspaces/jupiterone-io/graph-azure/node_modules/@jupiterone/integration-sdk/src/framework/execution/dependencyGraph.js:236:10)
at Object.executeStepDependencyGraph (/Users/aiwilliams/Workspaces/jupiterone-io/graph-azure/node_modules/@jupiterone/integration-sdk/src/framework/execution/dependencyGraph.js:59:28)
at Object.executeSteps (/Users/aiwilliams/Workspaces/jupiterone-io/graph-azure/node_modules/@jupiterone/integration-sdk/src/frame …
```
=> Publish source maps

CHANGELOG.md, src/errors.ts, src/framework/execution/__tests__/logger.test.ts, src/framework/execution/logger.ts
Closes #136 . I decided to not add a `logger.authError` function and opted to instead just enhance the existing messages with more information if we happen to come across an `IntegrationProviderAuth*` error.
=> Append additional message details for events related to provider auth error

packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/config.ts, packages/integration-sdk-private-test-utils/__fixtures__/instanceConfigWithoutEnv/src/index.ts, packages/integration-sdk-private-test-utils/__fixtures__/instanceWithDependentSteps/src/index.ts, packages/integration-sdk-private-test-utils/__fixtures__/javaScriptProject/src/index.js, packages/integration-sdk-private-test-utils/__fixtures__/typeScriptIntegrationProject/src/index.ts, packages/integration-sdk-private-test-utils/__fixtures__/typeScriptProject/src/index.ts, packages/integration-sdk-private-test-utils/__fixtures__/typeScriptVisualizeProject/src/index.ts, packages/integration-sdk-private-test-utils/__fixtures__/validationFailure/src/index.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md, yarn.lock
Updated all test fixtures to have a `src/index` file that exposes the `invocationConfig`.
Added an entry to the CHANGELOG to reflect a change that was made to the `integration-sdk-testing` package around changes to convention based loading as well.
Added missing devDependencies to the `integration-sdk-cli` package.
=> Remove deprecated convention based invocationConfig loading

.github/workflows/build.yml, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, packages/integration-sdk/README.md
Looks like independent versioning creates different tags and the publish workflow wasn't updated to handle that. I tested the `git describe` change locally and it properly resolves the commit to a tag now.
=> Fix git describe matching in publish

packages/integration-sdk-core/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
I saw that the publish result displayed a bunch of `src` files and realized that I forgot to do this.
=> Only publish dist from published packages

packages/integration-sdk-cli/package.json, packages/integration-sdk/CHANGELOG.md
We don't expose any types from the cli that require `@types/vis` to be installed for consumers to use it.
=> Move @types/vis from dependencies to devDependencies

packages/integration-sdk-dev-tools/README.md
Just a small change to the example tsconfig to make it match what we are actually doing in the integrations.
=> Update tsconfig in integration-dev-tools readme to include outDir

packages/integration-sdk-core/src/data/__tests__/converters.test.ts, packages/integration-sdk-core/src/data/converters.ts, packages/integration-sdk-core/src/data/tagging.ts, packages/integration-sdk/CHANGELOG.md
There's a form of this at https://github.com/JupiterOne/graph-cbdefense/blob/master/src/converters.ts#L105, it seemed good to bring it into this `convertProperties` function that is being used in a number of places.
I'd still like to make `createIntegrationEntity` do this work, but that will take more time to work through, and this will at least move closer to having the code in the converters of the sdk for re-used.
=> Add convertProperties parseTime option

packages/integration-sdk-cli/src/__tests__/cli-run-failure.test.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/apiClient.ts, packages/integration-sdk-core/src/types/index.ts, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-runtime/src/api/index.ts, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/events.test.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/events.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-testing/src/__tests__/context.test.ts, packages/integration-sdk-testing/src/logger.ts, packages/integration-sdk/CHANGELOG.md
Converted the IntegrationLogger implementation into an event emitter that can now be observed for events to publish. Part of the reason why I did this was because some interface needs to be exposed for publishing metrics and the logger felt like a good place to expose that since a metric really just a different type of event to log. Having to register the logger with a sync context started to feel dirty to me after implementing it, so this allows for us to remove that and allow the logger to mostly just function as a regular logger but now with hooks.
A small side benefit of this is that it removes the need for the `JUPITERONE_DISABLE_EVENT_LOGGING` environment variable hack that the j1-j1-integration needed. This also allows for us to remove the `axios` dependency from the …
=> Decouple logger and api client

packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/log.ts, packages/integration-sdk-core/src/types/index.ts, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-core/src/types/metric.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/index.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-runtime/src/metrics/__tests__/index.test.ts, packages/integration-sdk-runtime/src/metrics/index.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-testing/src/logger.ts
This builds on top of #231 and allows for `metric` events to be listened for. Our managed environment will handle collecting the `metric` events (pr for that coming soon).
=> Add interface for emitting metrics to be published

packages/integration-sdk-testing/src/__tests__/context.test.ts, packages/integration-sdk-testing/src/logger.ts, packages/integration-sdk/CHANGELOG.md
This makes the mock test logger a little easier to maintain (no need to add noop for every new function added) and also makes testing the logger's publishing behavior in the managed runtime a lot easier.
=> Expose silent version of runtime IntegrationLogger for createMockIntegrationLogger

packages/integration-sdk-cli/src/__tests__/cli-run-failure.test.ts, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk/CHANGELOG.md
This aims to help runtime incident response. These user-addressable errors do not need to be level:50. I need this for the Azure integration. We have some Hacker-created junk integrations that are generating alerts.
=> Log handled config validation errors at level:40

packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk/CHANGELOG.md
Since we are going to relying on log filtering for a bit, we might as well log the metric here. It's helpful for integration developers to see as well.
=> Log out metrics that were collected via logger.publishMetric

packages/integration-sdk-dev-tools/package.json, packages/integration-sdk/CHANGELOG.md, yarn.lock
Created a new integration and `yarn start` (`j1 collect`) doesn't "just work" for want of `ts-node`.
=> Fix missing ts-node

packages/integration-sdk-cli/src/visualization/__tests__/__snapshots__/generateVisHTML.test.ts.snap, packages/integration-sdk-cli/src/visualization/__tests__/generateVisHTML.test.ts, packages/integration-sdk-cli/src/visualization/generateVisHTML.ts, packages/integration-sdk-cli/src/visualization/generateVisualization.ts
Update the `j1-integration visualize` command to plot entities colored by type, as well as display the J1 type. 
I also changed the physics to bump entities away from eachother.
Formerly:
Now:
=> Visualize entities by type

packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/visualization/__tests__/__snapshots__/generateVisHTML.test.ts.snap, packages/integration-sdk-cli/src/visualization/__tests__/createMappedRelationshipNodesAndEdges.test.ts, packages/integration-sdk-cli/src/visualization/__tests__/generateVisHTML.test.ts, packages/integration-sdk-cli/src/visualization/__tests__/generateVisualization.test.ts, packages/integration-sdk-cli/src/visualization/__tests__/retrieveIntegrationData.test.ts, packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts, packages/integration-sdk-cli/src/visualization/generateVisHTML.ts, packages/integration-sdk-cli/src/visualization/generateVisualization.ts, packages/integration-sdk-cli/src/visualization/retrieveIntegrationData.ts, packages/integration-sdk-cli/src/visualization/types/IntegrationData.ts, yarn.lock
Taking the visualization tool a bit further for mapped relationships. 
As developers create mapped relationships in the integration SDK, visualizing the output of these mapped relationships can help to catch bugs during development.
This PR mainly creates three additional types on the `j1-integration visualize` graph:
1. Mapped relationships are shown on the graph as dashed edges (as opposed to solid edges)
2. The `MappedRelationship._mapping.sourceEntityKey` from a mapped relationship is expected to map back to an entity in the integration. When the `sourceEntityKey` is not found in the list of existing entities, the graph displays a red entity with the header **[MISSING ENTITY]**
3. The `MappedRelationship._mapping.targetRelationship` can exist in the integration, or may exist in …
=> J1 visualize mapped relationships

docs/integrations/development.md, packages/integration-sdk-core/src/errors.ts, packages/integration-sdk-core/src/types/jobState.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts, packages/integration-sdk-testing/src/jobState.ts, packages/integration-sdk/CHANGELOG.md, packages/integration-sdk/README.md
Gets an existing entity in the job state by `{ _key, _type }`. Throws if there is not *exactly* one match.
=> [J1-4221] Add getEntity() to the jobState

docs/integrations/development.md, packages/integration-sdk-core/src/data/__tests__/createIntegrationRelationship.test.ts, packages/integration-sdk-core/src/data/createIntegrationRelationship.ts, packages/integration-sdk-core/src/errors.ts, packages/integration-sdk-core/src/types/jobState.ts, packages/integration-sdk-core/src/types/relationship.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts, packages/integration-sdk-testing/src/jobState.ts, packages/integration-sdk/CHANGELOG.md, packages/integration-sdk/README.md
Allow mapped relationships to receive the source `_type`, either from the `source` property on `MappedRelationshipOptions`, or the optional `_mapping.sourceEntityType` property on `MappedRelationshipOptionsLiteral`.
Since this was related to #62 as well, I deprecated `createIntegrationRelationship` and exported `createDirectRelationship` and `createMappedRelationship`. These changes are in a separate commit from the primary functionality above.
=> Pass the source `_type` to mapped relationships.

packages/integration-sdk-cli/src/visualization/__tests__/createMappedRelationshipNodesAndEdges.test.ts, packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts, packages/integration-sdk-cli/src/visualization/generateVisualization.ts, packages/integration-sdk-cli/src/visualization/utils.ts, packages/integration-sdk/CHANGELOG.md
See https://airtable.com/tblq5xeQXHTFS1YnX/viw8UgryHmlyw1g27/recHxh0xfVGqefgk7?blocks=hide
The `visualize` command will NOT match the following targetEntity. The local matcher needs to be updated to make sure the `j1-integration visualize` command works properly:
```
const entity = {
_key: 'some-key',
_class: ['User'],
_type: 'user-type'
}
const targetEntity = {
_key: 'some-key',
_class: 'User',
_type: 'user-type'
}
```
In addition, `RelationshipMapping` interfaces use the `targetFilterKeys` property to declare which properties should be used to match target entities. This PR adds logic to match objects on sets of `targetFilterKey`s.
=> J1-4227: Match array/string _class in visualize

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
This package was being installed as a transitive dependency of another package, so it went unnoticed.
=> Add deepmerge package

.eslintrc, packages/cli/src/__tests__/cli-export.test.ts, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/__tests__/cli-sync.test.ts, packages/integration-sdk-dev-tools/config/eslint.json, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/__tests__/instance.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/events.test.ts, packages/integration-sdk-testing/src/__tests__/context.test.ts, packages/integration-sdk-testing/src/__tests__/recording.test.ts, packages/integration-sdk-testing/src/jobState.ts, packages/integration-sdk/CHANGELOG.md
#279 
- `jobState.addRelationships` floating promise in `@jupiterone/integration-sdk-testing`
- Various async fixes in test suites
I've noticed that sometimes tests are flaky in the CI. I think this PR should help. There were places in the tests that had floating promises.
We should ultimately switch to using `plugin:@typescript-eslint/recommended-requiring-type-checking`, but that will produce a lot of noise.
=> Fixes #279 - Introduce eslint rules that will help catch async errors

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts, packages/integration-sdk/CHANGELOG.md
schema when using _class with duplicate "required" properties
#293
=> Fixes #293 - "toMatchGraphObjectSchema" generates an invalid JSON

packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsInstanceDuplicateRelationshipTypes/src/steps/fetchAccounts.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsInstanceDuplicateRelationshipTypes/src/steps/fetchGroups.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsInstanceNoEntities/src/steps/fetchAccounts.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsInstanceWithRelationships/src/steps/fetchGroups.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsWithExistingGeneratedDocs/src/steps/fetchGroups.ts, packages/integration-sdk-private-test-utils/__fixtures__/docsWithoutExistingDoc/src/steps/fetchGroups.ts, packages/integration-sdk-private-test-utils/__fixtures__/typeScriptIntegrationProject/src/steps/fetchUsers.ts
RelationshipClass from @jupiterone/data-model
=> Fixes #301 - StepRelationshipMetadata in Step should require

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
Bumps `@jupiterone/data-model@0.9.0`, exposing `RelationshipClass.DENIES` from the following import:
```typescript
import { RelationshipClass } from '@juptierone/integration-sdk-core':
const DENIES = RelationshipClass.DENIES;
```
=> Release 3.1.0

packages/integration-sdk-cli/src/__tests__/__snapshots__/cli.test.ts.snap, packages/integration-sdk-cli/src/commands/document.ts
See #319 
Generates documentation with a **single** blank line between rows of text, in each of the following cases:
- Just Entities
- Just Relationships
- Both Entities and Relationships
- Neither Entities nor Relationships
```markdown
-->
The following entities are created:
| Resources | Entity \`_type\` | Entity \`_class\` |
| --------- | -------------- | --------------- |
| The Group | \`my_group\`     | \`Group\`         |
The following relationships are created/mapped:
| Source Entity \`_type\` | Relationship \`_class\` | Target Entity \`_type\` |
| --------------------- | --------------------- | --------------------- |
| \`the_root\`            | **HAS**               | \`my_account\`          |
<!--
```
=> Fixes #319: Make j1-integration document spacing consistent

docs/integrations/development.md
I found a few errors in this doc and wanted to throw up a PR to see if they should be changed.
I was getting errors from this link, and it looks like the repo file structure may have changed. It looks like this fixes it, but I don't have enough context to be 100% certain.
It may be worth checking to see if the same change needs to happen in other places too, but I intended this to be a quick-fix, and don't want to invest more time until I learn if this is helpful or not.
I found some links that looked like this:
and found a [source](https://gist.github.com/rachelhyman/b1f109155c9dafffe618) saying that github has a special format for header links.
A few small typos (missing letters or duplicate words)
=> Cleanup development.md typos

packages/integration-sdk-core/src/errors.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk/CHANGELOG.md
We're getting Sentry alerts for a few errors that are considered to be a kind that may only be resolved by the user changing something in their configuration. These are handled in the sdk runtime code in some special way, avoiding a `logger.error` call, and then re-thrown. The managed runtime sends them to Sentry, which we don't want to do. This adds a function to allow the managed runtime to see if it should not report these.
The places where these error types are handled in the SDK:
* [`IntegrationProviderAuthorizationError`](https://github.com/search?q=org%3AJupiterOne+IntegrationProviderAuthorizationError&type=Code)
* [`IntegrationProviderAuthenticationError`](https://github.com/search?q=org%3AJupiterOne+IntegrationProviderAuthenticationError&type=Code)
* …
=> Add shouldReportErrorToOperator to avoid alerts

packages/integration-sdk-core/src/data/createIntegrationRelationship.ts, packages/integration-sdk/CHANGELOG.md
There is no relationship property validation during the developer experience that would indicate to a developer that relationship properties cannot be `Object` or `Array` types, so devs are not notified until a failure in the integration run:
```
(6:16:26 PM) - [job_abort] - Aborting integration job. (reason=Error uploading collected data (API response: code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, message="2 validation error(s): - Error in relationships[0].repositoryPermissions (reason=OBJECTS_NOT_ALLOWED) - Error in relationships[0].buildPermissions (reason=OBJECTS_NOT_ALLOWED) (code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, statusCode=400, correlationId=91597af1-6ac5-49bf-853c-9b7f472104c4)").)
```
```
(6:19:08 PM) - [job_abort] - Aborting integration job. (reason=Error uploading collected …
```
=> Disallow Array/Object in AdditionalRelationshipProperties index sig

packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts, packages/integration-sdk-core/src/data/__tests__/createIntegrationRelationship.test.ts, packages/integration-sdk-core/src/types/entity.ts, packages/integration-sdk-core/src/types/relationship.ts
In the Artifactory integration, a call was made to `createMappedRelationship` with an actual persisted entity, and should have instead been made to `createDirectRelationship`. This was not noticed in code review, and ended up making it into production. 
In production, the integration failed with:
```
(1:38:55 PM) - [job_abort] - Aborting integration job. (reason=Error uploading collected data (API response: code=RELATIONSHIP_UPLOAD_FAILED_VALIDATION, message="2 validation error(s): - Error in relationships[0]._mapping.targetEntity._rawData (reason=Expected string | number | boolean | string[] | number[] | boolean[], but was object in _mapping.targetEntity._rawData) - Error in relationships[1]._mapping.targetEntity._rawData (reason=Expected string | number | boolean | string[] | number[] | …
```
=> Only allow primitives & arrays on mapped relationship target entities

packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/data/__tests__/createIntegrationEntity.test.ts, packages/integration-sdk-core/src/data/__tests__/createIntegrationRelationship.test.ts, packages/integration-sdk-core/src/data/createIntegrationEntity.ts, packages/integration-sdk-core/src/types/entity.ts, packages/integration-sdk/CHANGELOG.md, yarn.lock
Related to https://github.com/JupiterOne/data-model/pull/44. These changes will allow the Qualys integration to provide `id: [number, number]`, the two values by which a `Host` is identified in that system. These values will be added to the `id` property of the `Host` entities in a mapped relationship, `Service - SCANS -> Host`.
=> Entity.id as string | string[]

packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
I think it can be hard for external developers (or candidates working on coding challenges) to know where to look when `toMatchGraphObjectSchema()` matchers throw errors about invalid classes/schemas. This change is meant to make it easier for devs to know where to look for our data model schemas.
=> Add link to data-model when jest matchers fail to validate schema

package.json, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-testing/src/__tests__/jobState.test.ts, packages/integration-sdk-testing/src/jobState.ts, packages/integration-sdk/CHANGELOG.md
The azure integration has been hitting some issues where entity `id`s are returned with inconsistent casing. This makes the `findEntity` function useless in most cases, and prohibits us from identifying valid relationships across an environment. This PR allows users to pass a `keyNormalizationFunction` into an `InvocationConfig` that transforms keys before storing them (or retrieving them from) the `DuplicateKeyTracker`.
Closes #355
=> Add normalization function for DuplicateKeyTracker

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
Fixes #362 
Also removed the `step` property from logs, since there is already a `stepId` property attached in every step context: 
https://github.com/JupiterOne/sdk/blob/master/packages/integration-sdk-runtime/src/execution/dependencyGraph.ts#L314
=> 362 failure callback in logger

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
Add-on to #363. Unfortunately, that PR did not expose the callback in the `createIntegrationLogger` interface.
=> Expose onFailure callback in createIntegrationLogger

packages/cli/src/__tests__/cli-export.test.ts, packages/cli/src/__tests__/cli-import.test.ts, packages/cli/src/__tests__/utils/constants.ts, packages/cli/src/commands/j1Export.ts, packages/cli/src/commands/j1Import.ts, packages/cli/src/export/__tests__/bulkDownloadToJson.test.ts, packages/cli/src/export/bulkDownloadToJson.ts, packages/cli/src/export/exportAssetsToJson.ts, packages/cli/src/export/exportJsonAssetsToCsv.ts, packages/cli/src/import/importAssets.ts, packages/cli/src/import/importAssetsFromCsv.ts, packages/cli/src/validateApiKey.ts, packages/cli/src/validateOption.ts, packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/__tests__/cli-run-failure.test.ts, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/__tests__/cli-sync.test.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/commands/sync.ts, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/api/__tests__/index.test.ts, packages/integration-sdk-runtime/src/api/error.ts, packages/integration-sdk-runtime/src/api/index.ts, packages/integration-sdk/CHANGELOG.md
We should be able to use the old JWT user keys and the new service tokens for authorization. Thus, we cannot depend on having the account ID embedded in the access token. This change to the API client interface requires callers to provide an account ID and an access token instead of only a JWT user key. Since a public helper function is being removed, this will require a major version bump.
=> Support tokens for authorization

packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/index.ts, packages/integration-sdk-runtime/src/storage/types.ts
After reviewing the code, I think the easiest way to get this feature working is through the `GraphObjectStore` interface, which the `JobState` implementation interacts to get entities and relationships out of memory. I am thinking to have an implementation of the `GraphObjectStore` that wraps a `FileSystemGraphObjectStore` and a reference to an initiated `SynchronizationJob` and something like a `PersisterService`. When the `GraphObjectStore.flush()` function is invoked (including threshold-induced invocations), it will queue up requests to upload the data.
The managed runtime would use this this all the time, the CLI could be left unchanged or we could easily support an option like `--continuous-upload`.
Please let me know if you think this approach is sound and I'll continue to push it …
=> Upload entities and relationships continuously during ingestion

packages/integration-sdk-core/src/types/context.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk/CHANGELOG.md
I propose this change to allow the `managed-integration-runtime` to provide job execution history information to the integration. This will allow an integration to only ingest data since the last execution. It is related to #353, which is required to allow the integration to only add new data.
=> ExecutionContext.history

packages/integration-sdk-runtime/src/__tests__/index.test.ts, packages/integration-sdk-runtime/src/index.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/BucketMap.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/index.ts, packages/integration-sdk/CHANGELOG.md
Going to be using `BucketMap` in the managed `GraphObjectStore` implementation. Exposing `FileSystemGraphObjectStore` is not a necessary change, but I figured it didn't hurt to expose this to potential implementors who may want to extend it now that we are allowing a custom `graphObjectStore` to be passed into `executeIntegrationInstance`.
=> Expose BucketMap and FileSystemGraphObjectStore

packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk/CHANGELOG.md
Making some additional changes to the SDK and wanted to clean this up in the process because it was difficult to add new tests to this test suite due to the opinionated nature of the tests.
I think we should generally avoid using Jest hooks to create a bunch of global test variables and keep each test's state local to the individual test. Global test variables like this encourage bad test practices, can hide/introduce bugs in tests, and can make it difficult to add tests.
=> Refactor tests in executeIntegration.test.ts

packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/test/lateLoggerRegistration.ts, packages/integration-sdk-runtime/test/unregisterEventHandlers.ts, packages/integration-sdk/CHANGELOG.md
I tested this by removing all but two fake steps in the `graph-bamboo` project, linking `@jupiterone/integration-sdk-runtime` and executing with the following fake execution handlers:
```typescript
async function emitsMultipleResolve() {
await Promise.all([
(async () => {
await Promise.resolve();
throw new Error('Multiple Resolves Error #1');
})(),
(async () => {
await Promise.resolve();
throw new Error('Multiple Resolves Error #2');
})(),
]);
}
function emitsUnhandledRejection() {
async function throwsException() {
await Promise.resolve();
throw new Error('Unhandled Rejection');
}
void throwsException();
}
```
The console printed the following, showing both **Multiple Resolves Error #2** and **Unhandled Rejection**
```shell
nickdowmon@Nicks-MacBook-Pro graph-bamboohr % yarn start
yarn …
```
=> Local execution event emitters

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/synchronization/__tests__/uploadData.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
This should decrease the time it takes to upload all of our integration data by 3x and improve resiliency
=> Retry and increase concurrency on file uploads

packages/integration-sdk-cli/src/commands/collect.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/visualization/generateVisualization.ts, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/fileSystem.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/flushDataToDisk.test.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/flushDataToDisk.ts
Small change that should marginally improve integrations that produce a significant amount of graph objects locally.
- Less disk usage
- Faster reads
- Faster writes
=> Only write prettified files to the file system on local collection

packages/integration-sdk-runtime/src/execution/uploader.test.ts, packages/integration-sdk-runtime/src/execution/uploader.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-runtime/test/util/fixtures.ts
Put this in a separate PR as it will be easier to review and manage any feedback.
See here for motivation (thanks @mknoedel!): https://github.com/JupiterOne/sdk/pull/396/files#r545299685
I also decided to make some additional changes to the behavior around when we allow additional tasks to be pushed into the queue. I think it makes more sense to _not_ fail as fast as we can, but rather take the approach that we should upload as much data for a step as possible as we are already going to mark it as partial. The J1 synchronizer will handle edge cases that would cause issues (e.g. a relationship gets uploaded and one/both of the related entities failed to upload).
This idea is similar to the idea that we should be moving towards a world where integration steps do not fail fast in general …
=> Improve uploader queue to respect queue size instead of waiting for idle

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-core/src/types/storage.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
Some entities and relationships do not need to be stored on the
file system at all. We only need to store graph objects on the file
system if we later intend to fetch the data from the job state or
iterate over the `_type`. This PR introduces support for specifying
metadata in each step that can be used by the `FileSystemGraphObjectStore`
that will be used to omit specific data from being written to disk
entirely. The data will still get uploaded.
A longer term optimization would be actually leveraging the dependency graph to automatically generate this information. We can also make a follow-up improvement that removes the entire locking behavior during these cases because no step will rely on the unindexed data, so there is no reason to lock.
=> OPTIMIZATION: Support for omitting specific graph objects from file storage

packages/integration-sdk-runtime/src/synchronization/__tests__/uploadData.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk/CHANGELOG.md
There are sometimes intermittent credentials errors when running a managed integration on AWS Fargate. They consistently succeed with retry logic, so we don't want to log a bunch of warns.
=> Uploads should skip logging warn on CredentialsError

packages/integration-sdk-runtime/src/execution/__tests__/trimStringValues.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/utils/trimStringValues.ts
This is in response to [this ticket](https://dev.azure.com/jupiterone/Platform/_sprints/taskboard/Integrations%20Team/Platform/Sprint%2062?workitem=2100) where a company accidentally added a space to their accountId. We could change the UI, but I feel that it also makes sense to  check before running integrations as welll.
=> Trim integration config values

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/utils/bigMap.test.ts, packages/integration-sdk-runtime/src/execution/utils/bigMap.ts, packages/integration-sdk-testing/package.json, packages/integration-sdk/CHANGELOG.md
Never hit this issue before...
The Qualys integration run on a machine that has >30GB of memory. We allow V8 to use the entire ~30GB memory section using the `--max-old-space-size` Node option when the we start the process. The Qualys integration exited with an out of memory error despite only consuming ~20% of the total memory. I learned that V8 has an internal 1GB limit allocated to each `Map`, or 2^24 keys. We are hitting the 1GB limit. See: https://stackoverflow.com/questions/54452896/maximum-number-of-entries-in-node-js-map/54466812#54466812
This change implements a basic `BigMap` that is an array of maps. We start with a map with a maximum key space of 2,000,000 keys and will add a map every time we reach that threshold. I realize this is not perfect because some integrations will …
=> Allow duplicate key tracker to grow greater than V8 engine limit

packages/integration-sdk-core/package.json, packages/integration-sdk/CHANGELOG.md, yarn.lock
Support `Vendor.category: string | string[]`.
cc/ @kevincasey1222 this will make the change available once this is approved, versioned, published, and an integration moves to the new version.
=> Upgrade to data-model@^0.18.0

packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/data/rawData.ts, packages/integration-sdk-core/src/types/entity.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
The persister does schema validation on the `_rawData` value of entities that is different from this TypeScript type, which causes confusing upload errors like:
```
Error uploading collected data (API response: code=ENTITY_UPLOAD_FAILED_VALIDATION, message="1 validation error(s):
- Error in entities[0]._rawData (reason=Expected { [_: string]: { body: string | { [_: string]: unknown }; contentType: string | undefined; } } | undefined, but was object in _rawData)
").
```
This change will let Typescript tell us if we put in an array instead an object, thus preventing these errors:
Fixes #441
=> Update the EntityRawData type to be in-line with the persister

README.md
Just wanted to make this a bit clearer - somehow my local links got messed up and it wasn't immediately clear that a fresh install will require `yarn build`.
=> Add yarn build to readme development section

packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/commands/compare.ts, packages/integration-sdk-cli/src/commands/index.ts, packages/integration-sdk-cli/src/utils/diff.ts, packages/integration-sdk-cli/src/utils/exampleDataset.json, yarn.lock
Usage:
This is used when migrating integrations from the old sdk to the new sdk to ensure there are no unintended changes.
Helper text:
```
Usage: compare [options] <oldPath> <neoPath>
Compare the differences between two datasets that were downloaded from JupiterOne via the query: 
find * as e that RELATES TO as r * return e.*, r.*
Example Dataset: 
{
"type": "table",
"data": [
{
"e._objectType": "entity",
"e._key": "12345",
"e.name": "Name"
}
],
"totalCount": 1
}
Arguments:
oldPath                          relitive path to the dataset to compare against
neoPath                          relitive path to the new dataset
Options:
-logkey, --log-only-key-changes  Only log entities and relationships that have _key values that are not in the other dataset.
-h, --help …
```
=> add diffing functionality to the sdk

CHANGELOG.md, packages/integration-sdk-core/src/types/storage.ts, packages/integration-sdk-private-test-utils/src/graphObjectStore.ts, packages/integration-sdk-runtime/src/storage/memory.ts
Very often I find myself using the non-null assertion operator on properties I'm passing into the `jobState.findEntity()` method. Using non-null assertion is an antipattern in typescript IMO and this method should _explicitly_ handle the `undefined` case for safety's sake.
=> Allow `findEntity()` to accept `string | undefined`

packages/integration-sdk-runtime/src/execution/instance.ts
Some `Account` entities use integration instance variables as properties / `_key`s (in Tenable, [for example](https://github.com/JupiterOne/graph-tenable-cloud/blob/master/src/steps/account/converters.ts#L9)). When converting to the new SDK and running diffing operations, it's important to pass the same instance variables so that a complete diff can be executed.
```diff
{
-  tenable_account_e1f4b959-9907-48f8-80d3-76919a5eb545: {
-    _type: [
-      "tenable_account"
-    ]
-    _class: [
-      "Account"
-    ]
-    _source: "integration-managed"
-    displayName: "Tenable Nick Test"
-    properties: {
-      name: "Tenable Nick Test"
-      tag.AccountName: "Tenable Nick Test"
-    }
-  }
+  tenable_account_local-integration-instance: {
+    _type: [
+      "tenable_account"
+    ]
+ …
```
=> Allow overriding local integration instance variables

CHANGELOG.md, packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/commands/diff.ts, packages/integration-sdk-cli/src/commands/index.ts, packages/integration-sdk-cli/src/index.ts, yarn.lock
This builds on top of `j1-integration compare` but uses the exported `diffString()` function from `json-diff`, which gives pretty colorized diffs
```diff
{
tenable_user_2232707: {
properties: {
-      id: 2232707
+      id: "2232707"
}
}
tenable_scan_19: {
properties: {
-      id: 19
+      id: "19"
}
}
tenable_scan_13: {
properties: {
-      id: 13
+      id: "13"
}
}
tenable_scan_17: {
properties: {
-      id: 17
+      id: "17"
}
}
tenable_scan_15: {
properties: {
-      id: 15
+      id: "15"
}
}
...
```
=> Add j1-integration diff command for colorized diffs

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
```
- Added `j1-integration diff` command to ouptut colorized diffs of old/new
integrations.
- Allow overriding integration instance properties when running integrations
locally.
```
=> Release 6.8.0

packages/integration-sdk-cli/src/commands/diff.ts
Primarily updating the J1QL in help text:
```diff
-        'find * with _integrationInstanceId="abc-123" that RELATES TO * return tree',
+        'find * with _integrationInstanceId="abc-123" (that RELATES TO *)? return tree',
```
Also console logging `--- ENTITY DIFF ---` and `--- RELATIONSHIP DIFF ---` to separate the two sets of diffs exported from this method.
=> Update j1-integration diff output/helptext

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-runtime/src/execution/utils/seperateStepsByDependencyGraph.ts, packages/integration-sdk-testing/package.json
This change adds the ability to, in the integrationConfig, specify multiple dependency graphs that each step can be assigned to. These graphs will then be executed in the order specified.
This maintains backwards compatibility with existing integrations while allowing us to specify an integration step as needing to be last for the google-cloud role binding steps.
NOTE: I didn't need to change anything for local execution because of one side-effect of this change. If your step definition `dependsOn` a step that is no longer in your dependency graph, you will get a "Node does not exist" error. I thought this was a good way to handle this case so I left it as is, but if we want that to change and instead log a warning, then I would add back my changes to `prepareLocalStepCollection` that I …
=> Release 6.11.0

CHANGELOG.md, packages/integration-sdk-cli/src/__tests__/cli/__snapshots__/visualize-types.test.ts.snap, packages/integration-sdk-cli/src/commands/visualize-types.ts, packages/integration-sdk-cli/src/utils/generateVisHTML.ts, packages/integration-sdk-cli/src/visualization/__tests__/__snapshots__/generateVisHTML.test.ts.snap, packages/integration-sdk-cli/src/visualization/__tests__/generateVisHTML.test.ts
While working on a blog post, I noticed that the output of `j1-integration visualize-types` provides good content, but I didn't think screenshots would not look great in J1 marketing content because of the color scheme. Updated to use J1 primary colors.
<h2>Before</h2>
<h2>After</h2>
=> Use J1 colors in j1-integration visualize-types

CHANGELOG.md, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/step.ts
Right now data stored using the `setData` command is not shared between dependency graphs which is a real bummer for the graph-google-cloud project. This fixes that.
I pulled out the DataStore to where all the other shared stores are initialized.
=> share data store between all graphs in an integration run

CHANGELOG.md, packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts, packages/integration-sdk-runtime/src/execution/collection.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-testing/src/jobState.ts
- Tracked `_type`'s by step ID
- Log summary after each step in success or failure cases
Example:
```
17:33:55.586Z  INFO Local: Step summary (stepId=fetch-binary-authorization-policy)
summary: {"graphObjectTypeSummary":[{"_type":"google_binary_authorization_policy","total":1},{"_type":"google_cloud_project_has_binary_authorization_policy","total":1}]}
```
=> INT-1287 - Track summary of collected graph object `_type`'s

packages/integration-sdk-core/src/types/entity.ts
Removed a reference to temporary upload URLs, an older approach that is not used in the bulk upload system backing the integration SDK.
=> Improve documentation of entity raw data

CHANGELOG.md, packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts
Previously, the "placeholder entities" generated from j1-integration visualize included all of the properties in `targetEntity`, but in reality, target entities are unique only in their `targetFilterKeys`. 
Previous: 
Now:
=> Trim properties from placeholder entities created from j1-integration visualize

CHANGELOG.md, packages/integration-sdk-cli/src/visualization/__tests__/createMappedRelationshipNodesAndEdges.test.ts, packages/integration-sdk-cli/src/visualization/createMappedRelationshipNodesAndEdges.ts
=> Visualize dash placeholder entity outlines

CHANGELOG.md, packages/integration-sdk-cli/src/commands/visualize-types.test.ts, packages/integration-sdk-cli/src/commands/visualize-types.ts, packages/integration-sdk-cli/src/utils/getSortedJupiterOneTypes.ts, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts
This change allows developers to declare mapped relationships that are produced from a step. Users can specify mapped relationships like so:
```typescript
const step = {
id: 'step-id',
name: 'Step Name',
entities: [],
relationships: [],
mappedRelationships: [{
_type: 'mapped_relationship_type',
sourceType: 'source_entity_type',
_class: RelationshipClass.HAS,
target_type: 'target_entity_type',  // this is the target ("placeholder") entity
direction: RelationshipDirection.FORWARD,
}],
executionHandler,
}
```
This provides two main benefits:
1. Mapped relationships are recognized as **declared types**
2. Mapped relationships can be visualized in `yarn j1-integration visualize-types`
Check the test suites to verify behavior
=> Add mapped relationship metadata

CHANGELOG.md, packages/integration-sdk-core/src/types/index.ts, packages/integration-sdk-core/src/types/spec.ts, packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
This was formerly implemented in `graph-tenable`, see https://github.com/JupiterOne/graph-tenable-cloud/pull/117/files#diff-6fa1efb441a5cfd956cd83b787050f7ad1d9f17f3bfaf5b955d2357483ba057bR1
---
```
- Added `toImplementSpec` jest matcher
- Added `StepSpec` and `IntegrationSpecConfig` types in order to define
integration specifications
=> Add step spec

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/errors.test.ts, packages/integration-sdk-core/src/errors.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
In the azure integration, the way that we're making client API calls is causing almost every provider error, from every distinct step, to be grouped using the following trace:
```
at request (/opt/jupiterone/app/node_modules/@jupiterone/graph-azure/dist/azure/resource-manager/client.js:180:23)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
This change should help to fingerprint every unique error in sentry or other similar services.
=> Add cause.stack to IntegrationError stack trace

CHANGELOG.md, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/events.test.ts, packages/integration-sdk-runtime/src/synchronization/events.ts
See changelog below:
---
- Added support to publish job log events at level `info`, `warn`, and `error`.
Usage:
```ts
logger.publishInfoEvent({
name: IntegrationErrorEventName.Stats,
description: 'fetched 100000 records',
});
logger.publishWarnEvent({
name: IntegrationErrorEventName.MissingPermission,
description: 'Missing permission users.read',
});
logger.publishErrorEvent({
name: IntegrationErrorEventName.MissingPermission,
description: 'Missing permission users.read',
});
```
---
This change encourages stricter event names for info-, warn-, and error-level logs that should be shown to the user. The deprecated `publishEvent` method is still available to grant developers flexibility with job log events.
This also passes a level with the job log (`info`, `warn`, and `error`) that can be …
=> Add support to publish job log events at levels

CHANGELOG.md, package.json, packages/cli/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
- Added support to publish job log events at level `info`, `warn`, and `error`.
Usage:
```ts
logger.publishInfoEvent({
name: IntegrationErrorEventName.Stats,
description: 'fetched 100000 records',
});
logger.publishWarnEvent({
name: IntegrationErrorEventName.MissingPermission,
description: 'Missing permission users.read',
});
logger.publishErrorEvent({
name: IntegrationErrorEventName.MissingPermission,
description: 'Missing permission users.read',
});
```
- Added support for relative paths in `yarn j1-integration *` commands
=> Release 7.1.0

CHANGELOG.md, packages/integration-sdk-core/src/types/jobState.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-testing/src/jobState.ts
- Updated the interfaces for `jobState.findEntity` and `jobState.hasKey` to allow `undefined`. Oftentimes, we use optional chaining with `jobState.findEntity` or `jobState.hasKey`, so having the ability to pass `undefined` into these methods can make our code easier to read.
```ts
// without allowing `undefined`, we often need to assert values as `string`
const virtualMachineId = await jobState.findEntity(
nic.virtualMachine?.id as string,
);
// by allowing `undefined`, we can more safely use these methods without type assertions
const virtualMachineId = await jobState.findEntity(nic.virtualMachine?.id);
```
=> Allow undefined values in jobState.findEntity and jobState.hasKey

CHANGELOG.md, packages/integration-sdk-core/src/data/__tests__/createIntegrationEntity.test.ts, packages/integration-sdk-core/src/data/createIntegrationEntity.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts
This is a quality-of-life improvement that was triggered by a recent failure in the `graph-azure` project, which could have been prevented if `_key` were a required property.
This is a breaking change because integrations that do not already pass a `_key` property will need to explicitly set one now.
```
- **\*BREAKING\*** Explicitly require a `_key` property when using
`createIntegrationEntity()`. Previously, the `createIntegrationEntity()`
function allowed the `_key` property to be _optional_, and when not present,
the function automatically uses either `id` or `providerId` as the entity
`_key`.
This caused (entirely preventable) runtime errors if the given `source` data
did not have an `id` or `providerId` property available.
=> Explicitly require a _key property when using createIntegrationEntity

CHANGELOG.md, docs/integrations/development.md, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-core/src/types/context.ts, packages/integration-sdk-core/src/types/instance.ts, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-testing/src/context.ts
- Added the `loadExecutionConfig` lifecycle method to the `InvocationConfig`
interface. `loadExecutionConfig` loads shared configuration assets, such as
shared API credentials. Example:
```ts
import { fromTemporaryCredentials } from '@aws-sdk/credential-providers';
/**
* The AWS integration uses shared `fromTemporaryCredentials` across all of
* its clients.
*/
export function loadExecutionConfig({
config: { roleArn: string, externalId: string },
}) {
return {
credentials: fromTemporaryCredentials({
params: {
RoleArn: config.roleArn,
ExternalId: config.externalId,
RoleSessionName: `juptierone-${uuid()}`,
},
}),
};
}
```
---
See `docs/integrations.md` for more on using `loadExecutionConfig`: https://github.com/JupiterOne/sdk/blob/add-execution-config/docs/integrations/development.md#loadexec …
=> Add loadExecutionConfig hook

package.json, yarn.lock
- Explicitly upgrade `lerna` (See: https://github.com/lerna/lerna/blob/main/CHANGELOG.md#400-2021-02-10)
-------
Before:
```
▶ yarn audit
yarn audit v1.22.4
69 vulnerabilities found - Packages audited: 1498
Severity: 45 Moderate | 24 High
```
After:
```
▶ yarn audit
yarn audit v1.22.4
3 vulnerabilities found - Packages audited: 1335
Severity: 3 Moderate
```
**NOTE**: The remaining 3 vulnerabilities are currently unaddressable
=> Update packages with `yarn upgrade`

CHANGELOG.md, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
- Added optional `schema` property to `StepGraphObjectMetadata`. This allows
developers to provide the property schema to expect on entities,
relationships, and mapped relationships. This serves two uses:
1. Schemas can be used at runtime or test-time to verify that an entity has
the correct properties
2. The `j1-integration document` command could automatically produce consumer
documentation about the properties that an entity / relationship is
expected to have
=> Add optional `schema` property to graph object metadata

CHANGELOG.md, packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
- Updated jest matchers in the following way:
- added optional `_type` argument to `.toMatchGraphObjectSchema` matcher
- added optional `_type` and `_class` arguments to
`.toMatchDirectRelationshipSchema` matcher
This enables developers to simply pass the `StepEntityMetadata` and
`StepRelationshipMetadata` interfaces to these matchers. Usage:
```ts
expect(collectedEntities).toMatchGraphObjectSchema(Entities.USER);
expect(collectedRelationships).toMatchDirectRelationshipSchema(
Relationships.ACCOUNT_HAS_USER,
);
```
=> Add type to jest matcher

CHANGELOG.md, package.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json, yarn.lock
- Bumped `@types/jest@^27.1.0` in order to fix **Namespace 'NodeJS' has no exported member 'Global'.** issues captured here: https://github.com/facebook/jest/issues/11640
=> Bump jest packages @^27.1.0

packages/integration-sdk-cli/src/neo4j/neo4jGraphStore.ts
> Which GitHub repositories are accessible to outside collaborators?
Old query:
```cy
MATCH (n:github_repo)-[r:github_repo_allows_user]->(u:github_user{role:"OUTSIDE"})
RETURN n, u
```
New query:
```cy
MATCH (n:github_repo)-[ALLOWS]->(u:github_user{role:"OUTSIDE"})
RETURN n, u
```
=> Fix #629 - Neo4j store create relationships using `_class` as the label

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/neo4j/__tests__/neo4jUtilities.test.ts, packages/integration-sdk-cli/src/neo4j/neo4jUtilities.ts, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
Fixes #638. The Neo4j ingestion tool was ignoring properties with the value `false`.
With this fix, the following query is supported:
```cy
MATCH (user:User {
mfaEnabled: false
}) RETURN user
```
=> Fix #638 - Support Neo4j entity ingestion with `false` property values

packages/integration-sdk-core/src/types/entity.ts
#why so that it could be successfully resolved in packages dependent on the sdk.
=> Add export to EntityCoreProperties

packages/integration-sdk-core/src/data/__tests__/tagging.test.ts, packages/integration-sdk-core/src/data/converters.ts, packages/integration-sdk-core/src/data/tagging.ts
References #646
Probably a few different ways of handling this one, this approach uses JS coercion to let only string values that aren't `undefined` nor `null` pass through (our empty string lives there). What do you think of this? @austinkelleher
=> Add support for empty string values to assignTags

CHANGELOG.md, packages/integration-sdk-runtime/src/api/__tests__/index.test.ts, packages/integration-sdk-runtime/src/api/error.ts, packages/integration-sdk-runtime/src/api/index.ts
This PR adds a new environment variable, `SDK_API_CLIENT_MAX_TIMEOUT`, to configure the `maxTimeout` for the SDK's `ApiClient`.
The new `SDK_API_CLIENT_MAX_TIMEOUT` is an environment variable used to control the `retry.maxTimeout` property on the `Alpha` client the SDK uses to make calls to our public API routes. If no value is given for `SDK_API_CLIENT_MAX_TIMEOUT`, a default value of 10000 ms will be used. This is the same value the `Alpha` uses internally by default. `Alpha` also has other internal default values for `retry`. I have confirmed that if these other properties are `undefined` on the `retry` object we pass, `Alpha` will use its own defaults.
If the `SDK_API_CLIENT_MAX_TIMEOUT` is set but is not a number, then a new `IntegrationMaxTimeoutBadValue` error will be thrown. I …
=> Adding SDK_API_CLIENT_MAX_TIMEOUT environment variable

CHANGELOG.md, packages/integration-sdk-runtime/src/api/index.ts
This PR fixes an error where if `retryOptions` is `undefined`, there would be no default retry behavior.
=> Fixing an error where undefined retryOptions would not adopt defaults

CHANGELOG.md, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
- Log error `code` when an integration logs an error
- Throw an `IntegrationError` with code `INTEGRATION_UPLOAD_FAILED` when the
JupiterOne system responds with `RequestEntityTooLargeException`
- [#660] - Trigger fatal error when JupiterOne system responds with
`JOB_NOT_AWAITING_UPLOADS`
=> Fix #660 - Trigger fatal error when system responds with `JOB_NOT_AWAITING_UPLOADS`

CHANGELOG.md, packages/integration-sdk-testing/src/__tests__/executeStepWithDependencies.test.ts, packages/integration-sdk-testing/src/executeStepWithDependencies.ts
- Support `executeStepWithDependencies` for steps with no `dependencyGraphId`, even if `invocationConfig.dependencyGraphOrder` is present
=> Support executeStepWithDependencies for steps with no dependencyGraphId

packages/integration-sdk-benchmark/package.json, packages/integration-sdk-benchmark/src/benchmarks/FileSystemGraphObjectStore.addEntities.js, packages/integration-sdk-benchmark/src/benchmarks/InMemoryGraphObjectStore.addEntities.js, packages/integration-sdk-benchmark/src/benchmarks/JobState.addEntities.js, packages/integration-sdk-benchmark/src/index.js, packages/integration-sdk-benchmark/src/util/eventCollector.js
This PR adds two new benchmarks, updates an existing benchmark, and adds an `eventCollector` utility to make capturing and displaying benchmark information easier.
This partially addresses issue #643, but there is still more that could be done. This only benchmarks the `jobState.addEntities` function.
Benchmarks done on a 2019 MacBook Pro | 2.3 GHz 8-Core Intel Core i9 | 16 GB 2667 MHz DDR4
FileSystemGraphObjectStore#addEntities 100 Entities        46426.504 ops/sec
FileSystemGraphObjectStore#addEntities 1000 Entities       2479.691 ops/sec
FileSystemGraphObjectStore#addEntities 10000 Entities      128.303 ops/sec
FileSystemGraphObjectStore#addEntities 100000 Entities     9.504 ops/sec
InMemoryGraphObjectStore#addEntities 100   66478.234 ops/sec
InMemoryGraphObjectStore#addEntities 1000 …
=> [INT-3353] Updating and adding new benchmarks

packages/integration-sdk-cli/src/questions/__fixtures__/questions/invalid-results-are.yaml, packages/integration-sdk-cli/src/questions/__fixtures__/questions/results-are.yaml, packages/integration-sdk-cli/src/questions/managedQuestionFileValidator.test.ts, packages/integration-sdk-cli/src/questions/managedQuestionFileValidator.ts
I found that the question ingester is failing with 
```
Invalid question. Reason(s): question.queries[0].resultsAre should be equal to one of the allowed values
```
Specifically, it's using the following enum for validation:
```ts
export declare enum QueryResultsAre {
BAD = "BAD",
GOOD = "GOOD",
INFORMATIVE = "INFORMATIVE",
UNKNOWN = "UNKNOWN"
}
```
=> Enforce resultsAre in managed questions

CHANGELOG.md, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
In time it would be great to have the sdk attempt to re-shuffle batches in an attempt to get larger entities uploaded. However, this change will prevent infinite loops when shrinking rawData on entities whose **mapped properties** alone are enough to cause a batch to fail due to upload size > 6MB.
I've seen real-world examples in the Tenable integration where the properties on a **single vulnerability entity* was between 1-2MB. Seeing as batches can be up to 250 entities, just a few of these was enough to cause an upload failure. However, it is important to note that if these entities were in batches of size `1`, the upload would have succeeded.
=> throw upload error when shrunk payload too large

docs/integrations/development.md, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/commands/run.ts
Adding support to be able to pass --disable-schema-validation to the j1-integration run command (fix for Issue #626 )
=> INT-3984 - Support --disable-schema-validation option in run command

packages/integration-sdk-core/src/data/converters.ts
This PR deprecates convert properties. It should be removed in the next major version along with `getTime`.
=> [INT-3983] Deprecate Convert Properties

docs/integrations/development.md
Adding documentation for `j1` CLI.
Fix for issue #678
=> Adding j1 CLI documentation.

packages/integration-sdk-cli/src/commands/collect.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/commands/sync.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
- Adding `--upload-batch-size` option for `sync` and `run` commands.
- Removing no longer needed `--buffer-size` command.
=> Add `--upload-batch-size` option

CHANGELOG.md, packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/executeStepWithDependencies.ts, packages/integration-sdk-testing/src/jest.ts
- Added an optional `encounteredEntityKeys` property on `.toMatchStepMetadata()` to verify that any relationship `_fromEntityKey` and `_toEntityKey` has actually been encountered in the job state.
---
Usage remains the same as it was before:
```ts
test('fetch-users', async () => {
recording = setupProjectRecording({
directory: __dirname,
name: 'fetch-users',
});
const stepConfig = buildStepTestConfigForStep(Steps.USERS);
const stepResult = await executeStepWithDependencies(stepConfig);
expect(stepResult).toMatchStepMetadata(stepConfig);
});
```
However, tests will now fail with the following if `_fromEntityKey` or `_toEntityKey` target an entity that was _not_ encountered: 
```
● buildVpcRouteTableRels exec handler
Some direct relationships contain from/to entity keys which do not exist …
```
=> Enforce fromEntityKey and toEntityKey exist in job state when using .toMatchStepMetadata

packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/commands/sync.ts, packages/integration-sdk-runtime/src/execution/uploader.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/batchSize.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
Relationships are often much smaller and much more certain in size than entities. Allowing a separate batch size for relationships would allow us to upload much faster.
=> Adding Relationship Upload Batch Size option

packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts
The desired result of this change is to provide users an understanding of all possible steps available in an integration
Before a step is executed, the stepStartState is reference to see if the step is disabled. Prior to this change, if the step was disabled nothing would happen. Now, we add a job event log for the step indicating to the user that the step was disabled. Within the StepStartState, each step can be provided a reason for why it is disabled. It is the responsibility of the graph-* project to indicate why it was disabled. 
I believe this a positive change to exposing more information to the user about their integrations.
=> Add skipped steps to event log

CHANGELOG.md, docs/integrations/development.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-testing/package.json
There are circumstances where an integration should apply some type of
mutation to all relationships. We should introduce a new hook called
`beforeAddRelationship` that is similar to `beforeAddEntity`.
Example usage:
```typescript
export const invocationConfig: IntegrationInvocationConfig<IntegrationConfig> = {
instanceConfigFields: {},
integrationSteps: [],
beforeAddRelationship(context: IntegrationStepContext, relationship: Relationship): Relationship {
return {
...relationship,
customProp: true
};
}
};
```
=> Closes #757 - Introduce `beforeAddRelationship` hook

CHANGELOG.md, docs/integrations/development.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-testing/package.json
Example:
```ts
export const invocationConfig: IntegrationInvocationConfig<IntegrationConfig> = {
instanceConfigFields: {},
integrationSteps: [],
async beforeAddRelationship(context: IntegrationStepContext, relationship: Relationship): Relationship {
return Promise.resolve({
...relationship,
customProp: true
});
}
};
```
=> INT-4666 - Support async `beforeAddRelationship` hook

CHANGELOG.md, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-runtime/src/execution/__tests__/config.test.ts, packages/integration-sdk-runtime/src/execution/config.ts
closes #504 int-4941
Adds in `optional` option for instance config fields.
=> add optional option for instance config field

packages/integration-sdk-core/src/data/createIntegrationEntity.ts
This now matches the sdk-core version of it
https://github.com/JupiterOne/sdk/blob/main/packages/integration-sdk-core/src/data/tagging.ts#L62
-- We ran into an issue when trying to define an entity from Google Cloud which defines `tags` as a different `type` required by the `ProviderSourceData`.`type`.
This MR updates the type to match `assignTags` input
=> Update ProviderSourceData tags type

docs/integrations/development.md
The documentation for `j1-integration run` was out-of-date. Added
supported CLI arguments and relevant environment variables.
=> INT-5264 - Improve documentation of `j1-integration run`

packages/integration-sdk-runtime/src/synchronization/index.ts
We are seeing ERR_INVALID_ARG_TYPE errors that seem to be coming from
axios. However, we are losing a lot of helpful data about the error
when we handle convert the error into our custom IntegrationError. Specifically,
it seems that the `cause` (which contains the actual [error](https://github.com/JupiterOne/sdk/blob/26bc8d741cfdd621d253beaea2ba397ca2972017/packages/integration-sdk-runtime/src/synchronization/error.ts#L26)) is lost when logging (see pic).
While we investigate these errors, add a log statement to get more details on why axios threw.
=> INT-5226 Add log statement if an error occurs sending axios request

packages/integration-sdk-runtime/src/synchronization/index.ts
When we attempt to upload graph data and the upload fails, we retry using the
handleUploadDataChunkError function. However, if that function throws, we bail
immediately, which seems tobe happening in prod. As we investigate, add a warning
log if this happens.
=> INT-5336 Add warn log statement for when our handleError function throws

CHANGELOG.md, packages/integration-sdk-core/src/data/converters.ts
- fix: undefined and null values in number ptpv
- update changelog
=> Update `parseTimePropertyValue` number definition to allow undefined and null values

packages/integration-sdk-runtime/src/synchronization/shrinkBatchRawData.ts
When attempting to shrink _rawData, the helper function getPropSizeMapFromEntity
may be called. It goes through each key/value pair of a given entity and records
how large each field of the entity is. However, some values of an entity can be undefined,
which will cause Buffer.byteLength to throw. If there is an undefined value, set the size
to 0.
=> INT-5226 Fix the getPropSizeMapFromEntity function when shrinking _rawData

packages/integration-sdk-runtime/src/synchronization/__tests__/shrinkBatchRawData.test.ts, packages/integration-sdk-runtime/src/synchronization/shrinkBatchRawData.ts
Updated the getPropSizeMapFromEntity helper function so that it only sets
a size of 0 to undefined properties, not all falsey properties.
Additionally added a unit test that tests this new functionality.
=> INT-5226 Update getPropSizeMapFromEntity and add new unit test

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/commands/neo4j.ts, packages/integration-sdk-cli/src/neo4j/__tests__/neo4jGraphStore.test.ts, packages/integration-sdk-cli/src/neo4j/neo4jGraphStore.ts, packages/integration-sdk-cli/src/neo4j/uploadToNeo4j.ts, packages/integration-sdk-cli/src/neo4j/wipeNeo4j.ts, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
This PR adds the option to specify a different database name other than the default `neo4j` for Neo4j commands. This will allow us to add this requested functionality to Starbase.
=> Adding option to specify a different database name for Neo4j commands

CHANGELOG.md, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/__tests__/util/synchronization.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
We'd like to leverage the integration SDK to create sync jobs and upload data and avoid finalizing the job so we can process sync jobs in a different way.
=> Add j1-integration run --skip-finalize option

CHANGELOG.md, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/__tests__/cli-sync.test.ts, packages/integration-sdk-cli/src/__tests__/util/synchronization.ts, packages/integration-sdk-cli/src/commands/options.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/commands/sync.ts, packages/integration-sdk-core/src/types/synchronization.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/events.test.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/util/generateSynchronizationJob.ts, packages/integration-sdk-runtime/src/synchronization/events.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
The goal is documented in the code, but it may be helpful to provide a bit more concrete context.
We're working to load test Core and need a way to generate a lot of data that we upload to the Persister. The integration SDK has all the code we need to allow us to focus on writing data generation instead of data uploading in batches, upload error handling, etc. However, we plan to have many J1 accounts and many concurrent sync jobs per account, but do not want to manage a lot of integration instances. These changes allow us to execute bulk uploads (sync jobs) without the integration instances.
=> Add sync|run --source and --scope options

packages/integration-sdk-core/src/types/metric.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts
When the `IntegrationLogger` logs an error or a warn, the following events will be emitted respectively:
- `logged_error`
- `value`: 1
- `logged_warn`
- `value`: 1
=> INT-5593 - Emit metric when error or warn logged

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-testing/package.json
`logger.error` and `logger.warn` already write a log to the console and `publishMetric` _also_ writes a log to the console. We will now skip logging this metric data to avoid duplicate logs.
=> INT-5593 - Skip logging metric message on `logged_error` and `logged_warn`

CHANGELOG.md, packages/integration-sdk-runtime/src/logger/registerEventHandlers.test.ts, packages/integration-sdk-runtime/src/logger/registerEventHandlers.ts
The `multipleResolves` is not a strict failure. It is at times even expected behavior. As such, we should exclude it from calling `onFailure` which is a more serious error reporting mechanism than just logging the error at level `error`.
=> remove multipleResolves event from onFailure

CHANGELOG.md, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-testing/package.json
We have a theory that the `disk-usage` metric may be causing the Node.js process to hang in some situations. You can now disable this metric from emitted completely by specifying the `DISABLE_DISK_USAGE_METRIC` environment variable with any value.
=> INT-5868 - Allow skipping collection of `disk-usage` metric

CHANGELOG.md, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/step.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-runtime/src/metrics/index.ts
After graph data has been successfully added to the `JobState`, a custom metric is emitted that allows us to track the count of each graph object by `_type`.
The following new custom metrics have been added:
- `collected_entities`
- `collected_relationships`
- `collected_mapped_relationships`
=> INT-5717 - Publish custom graph data collection metrics

CHANGELOG.md, packages/integration-sdk-cli/src/commands/document.ts, packages/integration-sdk-cli/src/utils/getSortedJupiterOneTypes.test.ts, packages/integration-sdk-cli/src/utils/getSortedJupiterOneTypes.ts
- Added option to allow duplicate types in `getSortedJupiterOneTypes`
- Changed `j1-integration document` command to allow duplicate types
=> Allow duplicate types in document command

packages/integration-sdk-testing/src/__tests__/executeStepWithDependencies.test.ts, packages/integration-sdk-testing/src/__tests__/getStepExecutionOrder.test.ts, packages/integration-sdk-testing/src/config.ts, packages/integration-sdk-testing/src/executeStepWithDependencies.ts, packages/integration-sdk-testing/src/getStepExecutionOrder.ts, packages/integration-sdk-testing/src/jest.ts
I have had this change partially implemented for a while and was reminded of it when implementing #815 
Should keep current functionality and only changes how the function works if you define `dependencyStepIds`
=> Update executeStepWithDependencies to allow dependencyGraphId

CHANGELOG.md, packages/integration-sdk-cli/src/__tests__/cli-run.test.ts, packages/integration-sdk-cli/src/__tests__/util/synchronization.ts, packages/integration-sdk-cli/src/commands/options.ts
The `j1-integration run` command accepts at `--api-key` CLI flag. Previously, this CLI flag had a default value that would read the value of the `JUPITERONE_API_KEY` environment variable and modify the value using a regex replace. The modification of the value of `JUPITERONE_API_KEY` resulted in an invalid value being supplied in request headers. The JupiterOne API was responding with 401 Unauthorized consistently.
After discussing with the team, it turns out that the regex replacement on `JUPITERONE_API_KEY` was put in place to prevent the value of `JUPITERONE_API_KEY` from being logged to the console in the CLI help text message.
The usage of the `commander` CLI options has been updated to include specific help text messages instead of just logging the current value of each respective …
=> Fix #823 - Do not modify `JUPITERONE_API_KEY` env var in CLI defaults

packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts
Adding step disabled reason for when the step is unsupported due to a third party's API version.
=> Adding API_VERSION to DisabledStepReason enum

packages/integration-sdk-core/src/data/__tests__/tagging.test.ts, packages/integration-sdk-core/src/data/tagging.ts
The AWS integration (and, I suspect, other integrations), upload allow tags to have empty values (`''`). In this case, JupiterOne's `assignTags` functionality basically skips these tags altogether, preventing any useful querying capabilities for these types of tags.
This PR checks for tags with empty string values (`''`) and assigns them to the `.tags` array. 
In the future, I think we should consider adding _every_ tag name to the `.tags` property, instead of selectively choosing just those that match `/^true$/i`.
=> Add tags with value: '' to .tags property

packages/integration-sdk-cli/src/commands/document.ts
This PR reduces the logging in the cli's document command. Since this command is run on every `git commit` in graph repos, it generates a lot of extra noise
while going through normal workflows.
=> reduce logging in document command

CHANGELOG.md, packages/integration-sdk-cli/src/commands/document.ts, packages/integration-sdk-cli/src/utils/getSortedJupiterOneTypes.test.ts, packages/integration-sdk-cli/src/utils/getSortedJupiterOneTypes.ts
This change updates the automatic integration documentation generator strategy to avoid creating duplicate records for entities, relationships, and mapped relationships. There was a change that was introduced recently that allowed for duplicate records. In some integrations, relationships and mapped relationships have the same `_type` value and a different value for one/more of the `_class`, `sourceType`, `targetType`, and `direction` properties. Originally, the de-duplication code in the `j1-integration document` command used the `_type` value for entities and relationships as the de-dup key. The `_type` is insufficient, but we still must ensure that other important properties are considered in the de-dup process instead of blindly allowing duplicates.
The new approach removes allowing …
=> INT-7550 - fix duplicate integration data model doc rows

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
Introduce yarn caching and leverage `--frozen-lockfile` when installing packages.
=> NO-TICKET - Improve performance of SDK build

packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.test.ts, packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts
Before this PR, I was only adding the child sources to the array `childIngestionSources`, that means, I was not adding the steps that actually points to the ingestionSourceId in that array. With the previous implementation, there was no way to identify those steps in the UI. e.g.
Based on that image we were not able to obtain the `AWS Backup service` but `AWS Backup vault`. This PR adds the changes to obtain both in the command `generate-ingestion-sources-config`: 
1. The steps pointing to the `ingestionSourceId` 
2. The child steps or steps that depends on it.
=> INT-7562 - add steps using the ingestion source id to childIngestionSources

packages/integration-sdk-core/src/types/jobState.ts
The `hasKey` function has no asynchronous implementation, and awaiting `jobState.hasKey` can unexpectedly cause duplicate key errors in some specific edge cases (see https://github.com/JupiterOne/sdk/pull/694/files).
I believe this is a major version change, because it changes a public interface. Adopting projects should remove `await` anywhere this method is called.
=> Remove asynchronous hasKey

packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.test.ts, packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts
Reverts JupiterOne/sdk#886
I'm reverting this PR because we don't need the steps pointing to the `ingestionSourceId` in the `childIngestionSources`, we just want the children steps or steps that depends on the disabled steps.
=> Revert "INT-7562 - add steps using the ingestion source id to childIngestionSources"

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/api/__tests__/index.test.ts, packages/integration-sdk-runtime/src/api/index.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/batchSize.test.ts, packages/integration-sdk-testing/package.json, yarn.lock
Updates @lifeomic/alpha. This moves transitive dependency `aws-sdk` to `@aws-sdk` v3
=> chore: update @lifeomic/alpha

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.test.ts, packages/integration-sdk-cli/src/commands/generate-ingestion-sources-config.ts, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
Before this PR, the `generateIngestionSourcesConfigCommand` function only returned the stepIds in the `childIngestionSources` property. This implementation was fine, but now we want to show additional data related to the `childIngestionSources` on the frontend. To meet this requirement, I have modified the function to also return the `StepMetadata` (excluding the `executionHandler`).
=> [INT-8424] - modify generateIngestionSourcesConfigCommand to include child steps metadata in the childIngestionSources property 

packages/integration-sdk-cli/src/generator/stepsFlow.ts
In `j1-integration generate`, greater than one step is necessary for step dependencies to be applicable.
=> fix: only consider step dependencies prompt when more than one step

CHANGELOG.md, docs/integrations/development.md, packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-runtime/src/execution/__tests__/executeIntegration.test.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts
`afterExecution` is an optional hook function that can be provided. The function is called after an integration has executed, regardless of whether the execution was successful or not. An example of when you may decide to use this function is when you need to close out a globally configured client in an integration.
Example:
```typescript
import { IntegrationInvocationConfig } from '@jupiterone/integration-sdk-core';
import { IntegrationConfig } from './types';
export const invocationConfig: IntegrationInvocationConfig<IntegrationConfig> =
{
instanceConfigFields: {},
integrationSteps: [],
afterExecution(context) {
context.logger.info('Integration execution completed...');
},
};
```
=> Introduce `afterExecution` hook to integration invocation config

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/logger.ts, packages/integration-sdk-core/src/types/step.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/logger/index.ts, packages/integration-sdk-testing/package.json
This PR introduces a new log entry for each disabled child step to indicate that they have been skipped. To achieve this, a new `DisabledReason` has been implemented exclusively for child steps that are disabled. This `DisabledReason` provides a message like this:
```
Skipped step "{childStepName}". Step was disabled because parent step "{parentStepName}" was disabled. In order to enable this step, please check logs for more information about the parent step
```
when a child step is disabled.
=> Release 9.8.0 - add new log entry for each disabled child step

packages/integration-sdk-runtime/src/synchronization/index.ts
Troubleshooting these `UPLOAD_ERROR`s coming back from persister API. 
```
SyntaxError: Unexpected token < in JSON at position 0 
Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
at JSON.parse (<anonymous>)
at /opt/jupiterone/app/src/ecs/index.js:667257:21
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async parseErrorBody (/opt/jupiterone/app/src/ecs/index.js:667262:21)
at async de_InvokeCommandError (/opt/jupiterone/app/src/ecs/index.js:664777:15)
at async /opt/jupiterone/app/src/ecs/index.js:1441:24
at async /opt/jupiterone/app/src/ecs/index.js:5359:22
at async /opt/jupiterone/app/src/ecs/index.js:2843:42
at async /opt/jupiterone/app/src/ecs/index.js:1657:26
at async execute …
```
=> Log raw (unparsed) JSON response from UPLOAD_ERROR

packages/integration-sdk-runtime/src/execution/executeIntegration.ts
This message can produce _very_ long results in collectionResult which ends up getting split into multiple log entries which are un-parsable. Most of the information in this log can be found at the step level and probably does not need to be aggregated.
The message gets split into 8 parts in AWS integration, 3 in GCP, and 4 in Azure. In each of those integrations the message is not queryable due to how it is split.
```json
{
"name": "...",
"hostname": "...",
"pid": 1,
"accountId": "...",
"integrationInstanceId": "...",
"integrationDefinitionId": "...",
"source": "...",
"integrationJobId": "...",
"synchronizationJobId": "...",
"level": 30,
"collectionResult": {
"integrationStepResults": [
{
"id": "create-base-aws-account",
"name": "Create Base AWS Account",
"dependsOn": [], …
```
=> Fix long log message in runtime

packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/logger/__tests__/index.test.ts, packages/integration-sdk-runtime/src/logger/index.ts
Removes eventId from error description so that errors can be more easily grouped. Changes
```diff
- Step "Fetch IAM Users" failed to complete due to error. (errorCode="Throttling", errorId="2926a071-b776-4c6f-9449-c21062ecdb56", reason="Provider API failed at https://iam.amazonaws.com/?Action=GetAccessKeyLastUsed: 400 Rate exceeded")
+ Step "Fetch IAM Users" failed to complete due to error. (errorCode="Throttling", reason="Provider API failed at https://iam.amazonaws.com/?Action=GetAccessKeyLastUsed: 400 Rate exceeded")
```
The eventId will still be present on the logged payload, this just removes it from the description.
=> Remove error id from log message description

packages/integration-sdk-runtime/src/api/index.ts
Sometimes, loading AWS credentials from inside an ECS container fails and needs to be re-tried. The AWS SDK js v2 used a default of 3 retries, but the new AWS SDK js v3 uses a default of zero retries. 
The `@lifeomic/alpha` package was updated in https://github.com/JupiterOne/sdk/pull/903, and part of this update included bumping the AWS SDK version from v2 to v3 - removing default retries for these credential providers. As a result, integrations running on the SDK >v9.4.0 (including AWS, Jira, Google Workspace, and Okta) are experiencing frequent upload failures with `Could not load credentials from any provider`. In contrast, the second and third largest integrations, Google Cloud and Azure (which use an older version of the SDK), do not experience these types of upload failures.
There …
=> Increase Alpha default credential provider retries from 0 to 3

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
- Pass an instantiated credential provider to `@lifeomic/alpha` client so that 
credentials stop getting re-loaded when hitting the synchronization API from a 
private endpoint
=> Changelog for 9.9.1

packages/integration-sdk-runtime/src/execution/uploader.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/batchSize.test.ts, packages/integration-sdk-runtime/src/synchronization/batchBySize.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-runtime/src/synchronization/shrinkBatchRawData.ts
Currently we allow integrations to tune the size of the batches of entities/relationships uploaded to the persister api by setting the # of entities/relationships they’d like in each batch. Seeing as we’d like to keep our batched uploads sized  5MB  we should build our batches until they are adequately sized.
We will find that some integrations simply do not produce this much data, in which case we should upload everything for the job in single batch.
In the event that we cannot chunk by size, remove the raw data instead.
This will also prevent some UPLOAD_ERRORS or even UNEXPECTED_SYNCRONIZATION_ERROR since the batching will only allow chunks to be below 5MB.
=> Batching persister calls by size

CHANGELOG.md, lerna.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
- 'InMemoryGraphObjectStore' no longer stores a set amount of entities or relationships, rather it works by measuring size in bytes of graph objects by default.
=> Release 10.1.0

CHANGELOG.md, docs/integrations/development.md, packages/integration-sdk-cli/src/commands/collect.ts, packages/integration-sdk-cli/src/commands/options.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-cli/src/commands/sync.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts
Adds a `--noPretty` option to disable pretty printing of logs when running locally
=> Add no pretty option

CHANGELOG.md, packages/integration-sdk-dev-tools/config/jest.js
Removes depcrated way of setting ts-jest transform options. No more warnings on every test.
=> Remove TS-Jest deprecated code

packages/integration-sdk-cli/src/__tests__/options.test.ts, packages/integration-sdk-cli/src/commands/options.ts, packages/integration-sdk-cli/src/commands/run.ts, packages/integration-sdk-runtime/src/execution/uploader.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/batchSize.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
The `uploadBatchSize` and `uploadRelationshipsBatchSize` parameters are entirely unused, because they're piped down all the way to `uploadData` where the parameter is unused and instead it uses `uploadBatchSizeInBytes` instead (the last two lines in this PR).
This will be released in a major version update due to it being a breaking change to the interfaces/CLI commands.
=> Remove unused batch size (count) parameters

packages/integration-sdk-runtime/src/execution/uploader.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/synchronization/__tests__/shrinkBatchRawData.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-runtime/src/synchronization/shrinkBatchRawData.ts
With this, we can send through larger batch sizes from jupiter-managed-integration. First one targeted will be AWS via numeric feature toggle - https://app.launchdarkly.com/integrations/production/features/integration-aws-upload-batch-size-bytes/targeting
=> [CORE-3497] remove hard cap on upload batch size in bytes

packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts
This param is no longer used, I meant to remove it in #966 will release in v11 patch since it's related to the same breaking change.
=> [CORE-3497] drop unused param

.github/workflows/build.yml
This PR removes the windows checks. They are very slow and often fail on `yarn install` due to this slowness.
=> Remove Windows Checks

packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-runtime/src/execution/dependencyGraph.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/step.ts
This will give us the ability to limit the number of concurrent steps. Currently the value is the default (`POSITIVE_INFINITY`)
=> Add step concurrency to dependency graph

packages/integration-sdk-runtime/src/synchronization/__tests__/index.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts
Improves logging for uploadData
=> upload data improvements

packages/integration-sdk-core/src/data/createIntegrationEntity.ts
We have some entities where we don't upload rawData in purpose because they can be huge.
The current function in the SDK doesn't allow us to use itself if the source is undefined
=> Allow source in IntegrationEntityData to be undefined

.github/workflows/build.yml
I found a few issues with this workflow. You were running the workflow twice on every push, not using setup-node to configure the npm token, and not having concurrency enabled to better manage push spamming.
=> [No Ticket] - Cleanup GH workflow

packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
To avoid the use of disableClassMatch I have added in a way to remove required properties from the schema and will be applied at the end of the processing of the schema to ensure it is not re-added.
We already have the functionality to override the data-model type properties but not the required array.
=> Allow deletion of required properties from schema

packages/integration-sdk-testing/src/__tests__/jest.test.ts, packages/integration-sdk-testing/src/jest.ts
Currently when validating graph object's schema with `additionalProperties: false` you are required to add _rawData as a property ([As seen here](https://github.com/JupiterOne/graph-google-cloud/blob/597eb7bd798f4406d39f054fcdbff38040a040da/src/steps/service-usage/constants.ts#L28-L31))
This will remove automatically add the property to the schema to prevent this need.
=> Automatically include _rawData in schema for entities

packages/integration-sdk-core/src/types/storage.ts, packages/integration-sdk-runtime/src/storage/memory.test.ts, packages/integration-sdk-runtime/src/storage/memory.ts
Adding this `hasKey` function will aid in moving entity and key lookup fully to disk to reduce memory footprint.
=> add optional hasKey function to storage interface

packages/integration-sdk-core/src/types/config.ts, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts, packages/integration-sdk-runtime/src/execution/__tests__/jobState.test.ts, packages/integration-sdk-runtime/src/execution/duplicateKeyTracker.test.ts, packages/integration-sdk-runtime/src/execution/duplicateKeyTracker.ts, packages/integration-sdk-runtime/src/execution/executeIntegration.ts, packages/integration-sdk-runtime/src/execution/index.ts, packages/integration-sdk-runtime/src/execution/jobState.ts, packages/integration-sdk-runtime/src/execution/onDiskDuplicateKeyTracker.test.ts, packages/integration-sdk-runtime/src/execution/onDiskDuplicateKeyTracker.ts, packages/integration-sdk-testing/src/jobState.ts, yarn.lock
Based on feedback in #1068, the `DuplicateKeyTracker` seems like the best place for an initial pass at on-disk persistence of keys. I've added an initial `OnDiskDuplicateKeyTracker` based on `lmbd`. The use of it requires installing `lmdb` in the target project so that projects that have not adopted it don't install the `lmdb` dependency.
This should eliminate one of the two largest in-memory data stores. The other being the `FileSystemGraphObjectStore`'s key to on-disk location index map.
=> Add OnDiskDuplicateKeyTracker

packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts
Keep track of graphObjects iterated in memory
=> Fix iterate graph objects

CHANGELOG.md, lerna.json, package-lock.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-core/src/types/jobState.ts, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-entity-validator/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/FileSystemGraphObjectStore.ts, packages/integration-sdk-runtime/src/storage/FileSystemGraphObjectStore/__tests__/FileSystemGraphObjectStore.test.ts, packages/integration-sdk-runtime/src/synchronization/index.ts, packages/integration-sdk-testing/package.json
When graph objects are iterated, mark them as Readonly.
Clean up unnecessary debugging logs.
=> Mark graph object readonly 

CHANGELOG.md, lerna.json, package-lock.json, packages/cli/package.json, packages/integration-sdk-benchmark/package.json, packages/integration-sdk-cli/package.json, packages/integration-sdk-core/package.json, packages/integration-sdk-dev-tools/package.json, packages/integration-sdk-entities/package.json, packages/integration-sdk-entity-validator/package.json, packages/integration-sdk-http-client/package.json, packages/integration-sdk-private-test-utils/package.json, packages/integration-sdk-runtime/package.json, packages/integration-sdk-testing/package.json
This bumps the data-model package to pull in the update to `osType` on  the `Device` class. 
https://github.com/JupiterOne/jupiter-data-model/pull/39
=> Release 15.2.1

packages/integration-sdk-entity-validator/src/__tests__/validator.test.ts, packages/integration-sdk-runtime/src/api/__tests__/index.test.ts, packages/integration-sdk-runtime/src/api/index.ts
For https://jupiterone.atlassian.net/browse/INT-12936
=> Adds proxy support using the Alpha client
